const products = [
  {
    name: "IGLO EDGE",
    tagline: "Technology That Impresses",
    heroVideo: "./assets/Products/Windows/IGLO EDGE/hero.mp4",
    specs: {
      soundInsulation: "36-47 dB",
      gaskets: "3 EPDM gaskets",
      thermalTransmittance: "Uw = 0.66 W/(m²K)*",
      numberOfChambers: 7,
      installationDepth: "82 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO EDGE",
      detailVideo: "./assets/Products/Windows/IGLO EDGE/detail.mp4",
      description:
        "Our new, most technologically advanced window is distinguished by an excellent thermal insulation parameter of Uw = 0.66 W/(m2K)* and a modern, angular profile shape. The extremely good thermal insulation parameters are due, among other things, to the 7-chamber profile design and 3 EPDM gaskets, including the central gasket.",
      standardEquipment: [
        "Double-chamber glazing package Ug = 0.5 W/(m2K)",
        "Swisspacer Ultimate plastic warm frame",
        "V-perfect weld",
        "4 anti-theft strikers according to the size of the sash and the hardware system",
        "Microventilation",
        "DUBLIN aluminium window handle",
        "Handle misplacement locking mechanism",
        "Perimeter, glazing and central gaskets in black or grey",
        "Filling of the lower hardware groove",
        "Sill trim",
        "Wide selection of PVC veneer colours",
        "3 profile colours to choose from: white, brown or anthracite",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IGLO EDGE/structure1.png",
      "./assets/Products/Windows/IGLO EDGE/structure2.png",
    ],
  },
  {
    name: "IGLO Energy",
    tagline: "",
    heroVideo: "./assets/Products/Windows/IGLO Energy/hero.mp4",
    specs: {
      soundInsulation: "37-46 dB",
      gaskets: "3 EPDM gaskets",
      thermalTransmittance: "Uw = 0.71 W/(m2K)*",
      numberOfChambers: 7,
      installationDepth: "82 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO Energy",
      detailVideo: "./assets/Products/Windows/IGLO Energy/detail.mp4",
      description:
        "An innovative and original 7-chamber A-class profile made exclusively of primary materials. The world's first system using a central gasket made of foamed EPDM to ensure the best energy efficiency parameters. Iglo Energy windows also stand out for their perfect parameters in terms of water tightness, microventilation and resistance to wind.",
      standardEquipment: [
        "Double-chamber glazing package Ug = 0.5 W/(m2K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "4 anti-theft strikers according to the size of the sash and the hardware system",
        "Microventilation",
        "Aluminium window handle",
        "Handle misplacement locking mechanism",
        "Perimeter, glazing and central gaskets in black or grey",
        "Filling of the lower hardware groove",
        "Sill trim",
        "Wide selection of PVC veneer colours",
        "Profile available in two colours: white, brown",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IGLO Energy/structure1.png",
      "./assets/Products/Windows/IGLO Energy/structure2.png",
    ],
  },
  {
    name: "IGLO Energy Classic",
    tagline: "The best parameters concealed in modern design",
    heroVideo: "./assets/Products/Windows/IGLO Energy Classic/hero.mp4",
    specs: {
      soundInsulation: "36-42 dB",
      gaskets: "3 EPDM gaskets",
      thermalTransmittance: "Uw = 0.73 W/(m2K)*",
      numberOfChambers: 7,
      installationDepth: "82 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO Energy Classic",
      detailVideo: "./assets/Products/Windows/IGLO Energy Classic/detail.mp4",
      description:
        "A unique design where you can choose the square-shaped glazing bead to reflect the latest architectural trends. The remarkable thermal insulation parameters are ensured by the optimum 7-chamber profile structure, a specially designed sealing system made of foamed EPDM and glass packages with high thermal insulation parameters.",
      standardEquipment: [
        "double-chamber glazing package Ug = 0,5 W/(m2K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "V-perfect weld",
        "4 anti-theft strikers according to the size of the sash and the hardware system",
        "microventilation",
        "aluminium window handle",
        "handle misplacement locking mechanism",
        "perimeter, glazing and central gaskets in black or grey",
        "filling of the lower hardware groove",
        "sill trim",
        "wide selection of pvc veneer colours",
      ],
      profileColors: ["white", "anthracite", "bronze"],
    },
    structureImages: [
      "./assets/Products/Windows/IGLO Energy Classic/structure1.png",
      "./assets/Products/Windows/IGLO Energy Classic/structure2.png",
    ],
  },
  {
    name: "IGLO ENERGY ALUCOVER",
    tagline: "Redefining Design Excellence",
    heroVideo: "./assets/Products/Windows/IGLO ENERGY ALUCOVER/hero.mp4",
    specs: {
      soundInsulation: "36 - 42 dB*",
      gaskets: "3 EPDM gaskets",
      thermalTransmittance: "Uw = 0,76 W/(m2K)*",
      numberOfChambers: 7,
      installationDepth: "93 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO ENERGY ALUCOVER",
      detailVideo: "./assets/Products/Windows/IGLO ENERGY ALUCOVER/detail.mp4",
      description:
        "Experience the fusion of cutting-edge thermal insulation performance and contemporary design with Iglo Energy Alucover. Embrace boundless creativity with an extensive palette of colors, empowering you to fashion a unique and personalized style for every interior or building facade.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 4 anti-theft strikers with Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 4 colours: white, silver, light brown, brown",
        "Dublin window handle",
        "3-glazed (2-chamber) units infilled with argon gas, with Ug = 0.5 W/(m²K)",
        "Swisspacer Ultimate edge",
        "Rectangular glazing bead",
        "V-Perfect weld",
        "2 EPDM gaskets (external and internal) + 1 central gasket made of foamed EPDM, gaskets available in black",
        "Gasket filling the lower fittings groove",
        "2 mm full (closed) steel frame reinforcement, 'C' shaped steel sash reinforcement",
        "RAL matt varnish",
        "5-chamber PVC under-sill trim with gasket",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IGLO ENERGY ALUCOVER/structure1.png",
      "./assets/Products/Windows/IGLO ENERGY ALUCOVER/structure2.png",
    ],
  },
  {
    name: "IGLO 5",
    tagline: "High quality at an attractive price",
    heroVideo: "./assets/Products/Windows/IGLO 5/hero.mp4",
    specs: {
      soundInsulation: "36-44 dB",
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0,89 W/(m2K)*",
      numberOfChambers: 5,
      installationDepth: "70 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO 5",
      detailVideo: "./assets/Products/Windows/IGLO 5/detail.mp4",
      description:
        "A 5-chamber system featuring very good thermal insulation parameters. Our innovative solution is based on a snow-white A-class profile made exclusively of primary materials to ensure the highest quality. These windows are perfect for both warm and cold climates.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers with Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "sash lifter (lifting mishandling device - depending on window height)",
        "microventilation in tilt and turn windows",
        "hinge covers in 4 colours: white, silver, light brown, brown",
        "aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "galvanised steel glass-pane spacer optional Swisspacer Ultimate glass-pane spacer",
        "2 EPDM gaskets in black (external and internal)",
        "gasket filling the lower fittings groove",
        "1.5 mm steel reinforcement for frame and sash (2 mm for balcony door sash), 'c'-shaped",
        "profile core in white",
        "5-chamber PVC under-sill trim with gasket",
        "Profile available in two colours: white and brown",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IGLO 5/structure1.png",
      "./assets/Products/Windows/IGLO 5/structure2.png",
    ],
  },
  {
    name: "IGLO 5 Classic",
    tagline: "Proven solutions mean customer satisfaction",
    heroVideo: "./assets/Products/Windows/IGLO 5 Classic/hero.mp4",
    specs: {
      soundInsulation: "34-42 dB",
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0.83 W/(m²K)*",
      numberOfChambers: 5,
      installationDepth: "70 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO 5 Classic",
      detailVideo: "./assets/Products/Windows/IGLO 5 Classic/detail.mp4",
      description:
        "Windows appreciated by Customers across the globe. They feature not only very good thermal insulation parameters but also excellent aesthetic values. With a wide range of Renolit veneers and numerous additional options, we can create the windows that will meet the expectations of the most demanding Customers.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers with Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 4 colours: white, silver, light brown, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Galvanised steel glass-pane spacer optional Swisspacer Ultimate glass-pane spacer",
        "2 EPDM gaskets in black (external and internal)",
        "Gasket filling the lower fittings groove",
        "1.5 mm steel reinforcement for frame and sash (2 mm for balcony door sash), 'c'-shaped",
        "Profile core in white",
        "5-chamber PVC under-sill trim with gasket",
        "The profile is available in three colours: white, anthracite and bronze",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IGLO 5 Classic/structure1.png",
      "./assets/Products/Windows/IGLO 5 Classic/structure2.png",
    ],
  },
  {
    name: "IGLO Light",
    tagline: "Even more daylight",
    heroVideo: "./assets/Products/Windows/IGLO Light/hero.mp4",
    specs: {
      soundInsulation: "34 dB",
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0,88 W/(m2K)*",
      numberOfChambers: 5,
      installationDepth: "70 mm",
      profileClass: null,
    },
    detailSection: {
      title: "IGLO Light",
      tagline: "Even more daylight",
      detailVideo: "./assets/Products/Windows/IGLO Light/detail.mp4",
      description:
        "This 5-chamber and original system stands out for its high aesthetic values and thin frame and sash profiles. Compared to traditional systems, it has a 32% thinner movable post to improve the amount of daylight that reaches a room.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers with Silber-Look anti-corrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 4 colours: white, silver, light brown, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "Glass-pane spacer made of galvanised steel",
        "2 EPDM gaskets in black (external and internal)",
        "Gasket filling the lower fittings groove",
        "1.5 mm steel reinforcement for frame and sash (2mm for balcony door sash), 'c'-shaped",
        "Profile core in white",
        "5-chamber PVC under-sill trim with gasket",
        "V-Perfect welding",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IGLO Light/structure1.png",
      "./assets/Products/Windows/IGLO Light/structure2.png",
    ],
  },
  {
    name: "IGLO EXT",
    tagline: "Modern PVC balcony windows and doors that open outwards",
    heroVideo: "./assets/Products/Windows/IGLO EXT/hero.mp4",
    specs: {
      soundInsulation: "34 - 35 dB*",
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0.89 W/(m²K)*",
      numberOfChambers: 5,
      installationDepth: "70 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO EXT",
      detailVideo: "./assets/Products/Windows/IGLO EXT/detail.mp4",
      description:
        "Balcony windows and doors that open outwards stand out for their modern design and excellent thermal insulation performance. As standard, these windows have hidden fittings (invisible when closed), while balcony doors have door (surface) fittings. The Iglo EXT window and door system is ideal for those looking for modern design and high aesthetic values.",
      standardEquipment: [
        "Double-chamber glazing package Ug = 1.1 W/(m²K)",
        "Concealed MACO Multi-Power fittings in the window (invisible hinges when the window is closed), door fittings on balcony windows or balcony doors",
        "Double roller DM20 bolt for full (airtight) locking or locking with trickle ventilation",
        "Aluminium handle with double-sided insert",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "2 EPDM gaskets in black (external and internal)",
        "Gasket filling the lower fittings groove",
        "1.5 mm full (closed), steel, 'c'-shaped frame and sash reinforcement (2 mm for balcony door sashes)",
        "Profile core in white",
        "5-chamber PVC under-sill trim with gasket",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IGLO EXT/structure1.png",
      "./assets/Products/Windows/IGLO EXT/structure2.png",
    ],
  },
  {
    name: "IGLO PREMIER",
    tagline: "Modern outward opening tilt and turn windows",
    heroVideo: "./assets/Products/Windows/IGLO PREMIER/hero.mp4",
    specs: {
      soundInsulation: "34 - 35 dB*",
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0.89 W/(m²K)*",
      numberOfChambers: 5,
      installationDepth: "70 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO PREMIER",
      detailVideo: "./assets/Products/Windows/IGLO PREMIER/detail.mp4",
      description:
        "Original outward opening tilt and turn windows are based on an extremely warm 5-chamber A-class profile made exclusively of primary material. The system comes with double sealing and reliable fittings to ensure high utility values for years to come.",
      standardEquipment: [
        "Scissor hinges (invisible when the window is closed)",
        "Double roller DM20 bolt for full (airtight) locking or locking with trickle ventilation",
        "Double-chamber glazing package Ug = 1.1 W/(m²K)",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "2 EPDM gaskets in black (external and internal)",
        "Gasket filling the lower fittings groove",
        "1.5 mm full (closed), steel, 'c'-shaped frame and sash reinforcement (2 mm for balcony door sashes)",
        "Profile core in white",
        "5-chamber PVC under-sill trim with gasket",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IGLO PREMIER/structure1.png",
      "./assets/Products/Windows/IGLO PREMIER/structure2.png",
    ],
  },
  {
    name: "IDEAL NEO AD",
    tagline: "More than modern design",
    heroVideo: "./assets/Products/Windows/IDEAL NEO AD/hero.mp4",
    specs: {
      soundInsulation: "36 dB",
      gaskets: "2 gaskets",
      thermalTransmittance: "Uw = 0.79 W/(m²K)*",
      numberOfChambers: 6,
      installationDepth: "76 mm",
      glassPackages: "24-54 mm",
      profileClass: "B",
    },
    detailSection: {
      title: "IDEAL NEO AD",
      detailVideo: "./assets/Products/Windows/IDEAL NEO AD/detail.mp4",
      description:
        "Slim and symmetrical profiles refer to current design trends and give lightness and elegance to the windows. Extremely narrow profile combinations mean even more light in the rooms. An attractive solution for both new built and renovation.",
      standardEquipment: [
        "Double-chamber glazing package Ug = 0.5 W/(m²K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "4 anti-theft strikers according to the size of the sash and the hardware system",
        "Microventilation",
        "Aluminium window handle",
        "Handle misplacement locking mechanism",
        "Perimeter, glazing and gaskets in black or grey",
        "Filling of the lower hardware groove",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IDEAL NEO AD/structure1.png",
      "./assets/Products/Windows/IDEAL NEO AD/structure2.png",
    ],
  },
  {
    name: "IDEAL NEO MD",
    tagline: "More than modern design",
    heroVideo: "./assets/Products/Windows/IDEAL NEO MD/hero.mp4",
    specs: {
      soundInsulation: "36 dB",
      gaskets: "3 seals",
      thermalTransmittance: "Uw = 0.76 W/(m²K)*",
      numberOfChambers: 6,
      installationDepth: "76 mm",
      glassPackages: "24-54 mm",
      profileClass: "B",
    },
    detailSection: {
      title: "IDEAL NEO MD",
      detailVideo: "./assets/Products/Windows/IDEAL NEO MD/detail.mp4",
      description:
        "Slim and symmetrical profiles refer to current design trends and give lightness and elegance to the windows. Extremely narrow profile combinations mean even more light in the rooms. An attractive solution for both new built and renovation.",
      standardEquipment: [
        "Double-chamber glazing package Ug = 0.5 W/(m²K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "4 anti-theft strikers according to the size of the sash and the hardware system",
        "Microventilation",
        "Aluminium window handle",
        "Handle misplacement locking mechanism",
        "Perimeter, glazing and central gaskets in black or grey",
        "Filling of the lower hardware groove",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IDEAL NEO MD/structure1.png",
      "./assets/Products/Windows/IDEAL NEO MD/structure2.png",
    ],
  },
  {
    name: "IDEAL NEO MD-FS",
    tagline: "In harmony with the architecture",
    heroVideo: "./assets/Products/Windows/IDEAL NEO MD-FS/hero.png",
    specs: {
      soundInsulation: "36 dB",
      gaskets: "3 gaskets",
      thermalTransmittance: "Uw = 0.73 W/(m²K)*",
      numberOfChambers: 6,
      installationDepth: "76 mm",
      glassPackages: "36-68 mm",
      profileClass: null,
    },
    detailSection: {
      title: "IDEAL NEO MD-FS",
      detailVideo: "./assets/Products/Windows/IDEAL NEO MD-FS/detail.png",
      description:
        "IDEAL NEO MD-FS is an extremely attractive design proposition for customers who value timeless style. A simple, symmetrical, cubist shape is the distinguishing feature of the system. Sharp angles and geometric architecture, and at the same time visual lightness of the structure.",
      standardEquipment: [
        "Double-chamber glazing package Ug = 0.5 W/(m²K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "4 anti-theft strikers according to the size of the sash and the hardware system",
        "Microventilation",
        "Aluminium window handle",
        "Handle misplacement locking mechanism",
        "Perimeter, glazing and central gaskets in black or grey",
        "Filling of the lower hardware groove",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IDEAL NEO MD-FS/structure1.png",
      "./assets/Products/Windows/IDEAL NEO MD-FS/structure2.png",
    ],
  },
  {
    name: "IDEAL NEO MD MONOBLOCK",
    tagline: null,
    heroVideo: "./assets/Products/Windows/IDEAL NEO MD MONOBLOCK/hero.png",
    specs: {
      soundInsulation: "36 dB",
      gaskets: "3 gaskets",
      thermalTransmittance: "Uw = 0.76 W/(m²K)*",
      numberOfChambers: 6,
      installationDepth: "76 mm / 122 mm / 142 mm / 162 mm",
      glassPackages: "24-52 mm",
      profileClass: null,
    },
    detailSection: {
      title: "IDEAL NEO MD MONOBLOCK",
      detailVideo: "./assets/Products/Windows/IDEAL NEO MD MONOBLOCK/detail.png",
      description:
        "Monoblock frames are designed for the construction of windows installed within a layer of insulation. The wide range of Monoblock frame sizes (76 mm, 122 mm, 142 mm, 162 mm) allows for appropriate selection depending on the insulation thickness. A special shelf (window sill) located on the outer side of the frame aesthetically covers the insulation around the window perimeter, preventing thermal bridges. The inner rebate of the Monoblock frame ensures aesthetic installation from the room interior without the need for gypsum finishing.",
      standardEquipment: [],
    },
    structureImages: [
      "./assets/Products/Windows/IDEAL NEO MD MONOBLOCK/structure1.png",
      "./assets/Products/Windows/IDEAL NEO MD MONOBLOCK/structure2.png",
    ],
  },
  {
    name: "IDEAL NEO MD RENOVATION",
    tagline: null,
    heroVideo: "./assets/Products/Windows/IDEAL NEO MD RENOVATION/hero.png",
    specs: {
      soundInsulation: "36 dB",
      gaskets: "3 gaskets",
      thermalTransmittance: "Uw = 0.76 W/(m²K)*",
      numberOfChambers: "5/6",
      installationDepth: "76 mm",
      glassPackages: "24-52 mm",
      profileClass: null,
    },
    detailSection: {
      title: "IDEAL NEO MD RENOVATION",
      detailVideo: "./assets/Products/Windows/IDEAL NEO MD RENOVATION/detail.png",
      description:
        "The renovation frame system is designed for window installation without dismantling old frames. This solution uses special renovation frames with a masking profile that surrounds the existing wooden frame, creating a clean inner band. On the exterior, special housing profiles can be applied. The masking profiles are available in different widths (40 mm, 70 mm), and can also be trimmed to fit specific installation requirements.",
      standardEquipment: [],
    },
    structureImages: [
      "./assets/Products/Windows/IDEAL NEO MD RENOVATION/structure1.png",
      "./assets/Products/Windows/IDEAL NEO MD RENOVATION/structure2.png",
    ],
  },
  {
    name: "IDEAL 7000 NL",
    tagline: "In harmony with the architecture",
    heroVideo: "./assets/Products/Windows/IDEAL 7000 NL/hero.png",
    specs: {
      soundInsulation: "36 dB",
      gaskets: "2 gaskets",
      thermalTransmittance: "Uw = 0.82 W/(m²K)*",
      numberOfChambers: 5,
      installationDepth: "120 mm",
      glassPackages: "24-54 mm",
      profileClass: null,
    },
    detailSection: {
      title: "IDEAL 7000 NL",
      detailVideo: "./assets/Products/Windows/IDEAL 7000 NL/detail.mp4",
      description:
        "The IDEAL 7000 NL system is the perfect solution for the Dutch market. With its 120 mm wide frame featuring external rebates, it allows for easy, fast, and aesthetically pleasing window installation in buildings made of facing brick (clinker) without requiring additional masonry work.",
      standardEquipment: [
        "Glazing package 24 mm, Ug = 1.1 W/(m²K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "4 anti-theft strikers according to the size of the sash and the hardware system",
        "Microventilation",
        "Aluminium window handle - Hoppe",
        "Handle misplacement locking mechanism",
        "Perimeter, glazing and gaskets in black or grey",
        "Filling of the lower hardware groove",
        "Profile available in 3 colors: white, anthracite, cream",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/IDEAL 7000 NL/structure1.png",
      "./assets/Products/Windows/IDEAL 7000 NL/structure2.png",
    ],
  },
  {
    name: "MB-86N SI",
    tagline: "Excellent parameters and durability of aluminium",
    heroVideo: "./assets/Products/Windows/MB-86N SI/hero.mp4",
    specs: {
      soundInsulation: null,
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0.76 W/(m²K)*",
      numberOfChambers: 3,
      installationDepth: "77 mm",
      profileClass: null,
    },
    detailSection: {
      title: "MB-86N SI",
      detailVideo: "./assets/Products/Windows/MB-86N SI/detail.mp4",
      description:
        "MB-86N SI aluminium windows stand out for their excellent thermal insulation parameters and modern design. With over 200 colours to choose from and numerous additional options, they offer full customisation and can be fitted with Smart Home solutions for enhanced convenience.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers with Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 3 colours: white, silver, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Glass-pane spacer made of galvanised steel",
        "1 EPDM gasket + 1 central gasket made of foamed EPDM, gaskets available in black",
        "RAL matt colours: white (9016), anthracite (7016)",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/MB-86N SI/structure1.png",
      "./assets/Products/Windows/MB-86N SI/structure2.png",
    ],
  },
  {
    name: "MB-79N SI",
    tagline: "Choose Energy Efficiency",
    heroVideo: "./assets/Products/Windows/MB-79N SI/hero.png",
    specs: {
      soundInsulation: null,
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0.81 W/(m²K)*",
      numberOfChambers: 3,
      installationDepth: "70 mm",
      profileClass: null,
    },
    detailSection: {
      title: "MB-79N SI",
      detailVideo: "./assets/Products/Windows/MB-79N SI/detail.mp4",
      description:
        "The new line of aluminium windows with increased thermal insulation, equipped with insulating inserts and a two-component central gasket, ensures lower heating bills. Its modern design with over 200 colour options and many additional features makes it a perfect choice for demanding customers.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers with Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 3 colours: white, silver, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Glass-pane spacer made of galvanised steel",
        "1 EPDM gasket + 1 central gasket made of foamed EPDM, gaskets available in black",
        "RAL matt colours: white (9016), anthracite (7016)",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/MB-79N SI/structure1.png",
      "./assets/Products/Windows/MB-79N SI/structure2.png",
    ],
  },
  {
    name: "MB-70HI",
    tagline:
      "Lightweight and durable aluminium windows for long-lasting comfort",
    heroVideo: "./assets/Products/Windows/MB-70HI/hero.mp4",
    specs: {
      soundInsulation: null,
      gaskets: "3 EPDM gaskets",
      thermalTransmittance: "Uw = 0.96 W/(m²K)*",
      numberOfChambers: 3,
      installationDepth: "70 mm",
      profileClass: null,
    },
    detailSection: {
      title: "MB-70HI",
      detailVideo: "./assets/Products/Windows/MB-70HI/detail.mp4",
      description:
        "Aluminium windows made using this system can be used in both individual buildings and aluminium facades. The lightweight and durable construction ensures a high level of comfort for many years of use.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers and Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 3 colours: white, silver, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Glass-pane spacer made of galvanised steel",
        "1 EPDM gasket + 1 central gasket made of foamed EPDM, gaskets available in black",
        "RAL matt colour: white (9016), anthracite (7016)",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/MB-70HI/structure1.png",
      "./assets/Products/Windows/MB-70HI/structure2.png",
    ],
  },
  {
    name: "MB-70",
    tagline:
      "Modern aluminium system with excellent thermal and acoustic insulation",
    heroVideo: "./assets/Products/Windows/MB-70/hero.mp4",
    specs: {
      soundInsulation: null,
      gaskets: "3 EPDM gaskets",
      thermalTransmittance: "Uw = 1.06 W/(m²K)*",
      numberOfChambers: 3,
      installationDepth: "70 mm",
      profileClass: null,
    },
    detailSection: {
      title: "MB-70",
      detailVideo: "./assets/Products/Windows/MB-70/detail.mp4",
      description:
        "The MB-70 system is a modern aluminium solution designed for the production of exterior architectural elements that require thermal and acoustic insulation. It offers durability, performance, and elegant design suitable for various building styles.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers and Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 3 colours: white, silver, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Glass-pane spacer made of galvanised steel",
        "1 EPDM gasket + 1 central gasket made of foamed EPDM, gaskets available in black",
        "RAL matt colour: white (9016), anthracite (7016)",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/MB-70/structure1.png",
      "./assets/Products/Windows/MB-70/structure2.png",
    ],
  },
  {
    name: "MB-45",
    tagline: "Modern aluminium system for versatile interior design",
    heroVideo: "./assets/Products/Windows/MB-45/hero.mp4",
    specs: {
      soundInsulation: null,
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: null,
      numberOfChambers: 2,
      installationDepth: "45 mm",
      profileClass: null,
    },
    detailSection: {
      title: "MB-45",
      detailVideo: "./assets/Products/Windows/MB-45/detail.mp4",
      description:
        "The MB-45 aluminium window system allows for the creation of diverse interior designs. It combines durability with a modern appearance, making it ideal for projects that require a refined aesthetic without the need for thermal insulation.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers and Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 3 colours: white, silver, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Glass-pane spacer made of galvanised steel",
        "2 EPDM gaskets available in black",
        "RAL matt colour: white (9016), anthracite (7016)",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/MB-45/structure1.png",
      "./assets/Products/Windows/MB-45/structure2.png",
    ],
  },
  {
    name: "SOFTLINE - 68, 78, 88",
    tagline: "Durability and beauty of nature",
    heroVideo: "./assets/Products/Windows/SOFTLINE - 68, 78, 88/hero.mp4",
    specs: {
      soundInsulation: null,
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "68 Uw = 1.08* / 78 Uw = 0.9** / 88 Uw = 0.8***",
      numberOfChambers: null,
      installationDepth: "68/78/88 mm",
      profileClass: null,
    },
    detailSection: {
      title: "SOFTLINE - 68, 78, 88",
      detailVideo: "./assets/Products/Windows/SOFTLINE - 68, 78, 88/detail.mp4",
      description:
        "Our wooden windows combine the highest quality craftsmanship, eco-friendly materials, and classic elegance. Exceptional durability is achieved through an aluminium bead that protects the wood from UV radiation and moisture. The Softline series features beautifully rounded profiles with smooth, shiny surfaces and is available in pine and meranti variants.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers and Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 3 colours: white, silver, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Glass-pane spacer made of galvanised steel",
        "Drip cap facilitating water drainage",
        "2 EPDM gaskets",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/SOFTLINE - 68, 78, 88/structure1.png",
      "./assets/Products/Windows/SOFTLINE - 68, 78, 88/structure2.png",
    ],
  },
  {
    name: "DUOLINE - 68, 78, 88",
    tagline: "Unique combination of wood and aluminium",
    heroVideo: "./assets/Products/Windows/DUOLINE - 68, 78, 88/hero.mp4",
    specs: {
      soundInsulation: null,
      gaskets: "3 Gaskets",
      thermalTransmittance: "68 Uw = 0.90* / 78 Uw = 0.84** / 88 Uw = 0.79**",
      numberOfChambers: null,
      installationDepth: "68/78/88 mm + spacer bar 14 mm",
      profileClass: null,
    },
    detailSection: {
      title: "DUOLINE - 68, 78, 88",
      detailVideo: "./assets/Products/Windows/DUOLINE - 68, 78, 88/detail.mp4",
      description:
        "DUOLINE windows combine the timeless beauty of natural wood with the modern durability of aluminium. This unique hybrid structure ensures excellent insulation, long-lasting performance, and elegant aesthetics. Numerous customization options allow you to tailor the windows perfectly to your architectural and personal needs.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers and Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 3 colours: white, silver, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Glass-pane spacer made of galvanised steel",
        "Drip cap facilitating water drainage",
        "3 EPDM gaskets",
      ],
    },
    structureImages: [
      "./assets/Products/Windows/DUOLINE - 68, 78, 88/structure1.png",
      "./assets/Products/Windows/DUOLINE - 68, 78, 88/structure2.png",
    ],
  },
];

export default products;
