const products = {
  windows: [
    // Windows
    {
      name: "IGLO EDGE",
      tagline: "Une technologie qui impressionne",
      heroVideo: "./assets/Products/Windows/IGLO EDGE/hero.mp4",
      specs: {
        soundInsulation: "36-47 dB",
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 0.66 W/(m²K)*",
        numberOfChambers: 7,
        installationDepth: "82 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO EDGE",
        detailVideo: "./assets/Products/Windows/IGLO EDGE/detail.mp4",
        description:
          "Notre nouvelle fenêtre, la plus avancée technologiquement, se distingue par un excellent paramètre d’isolation thermique de Uw = 0,66 W/(m2K)* et une forme de profil moderne et angulaire. Les performances d’isolation remarquables sont dues, entre autres, à la conception du profil à 7 chambres et aux 3 joints EPDM, dont un joint central.",
        standardEquipment: [
          "Vitrage double chambre Ug = 0,5 W/(m2K)",
          "Intercalaire chaud Swisspacer Ultimate",
          "Soudure V-Perfect",
          "4 gâches anti-effraction selon la taille de l’ouvrant et la quincaillerie",
          "Micro-ventilation",
          "Poignée de fenêtre en aluminium DUBLIN",
          "Sécurité de fausse manœuvre",
          "Joints périphériques, de vitrage et central en noir ou gris",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Habillage d’appui",
          "Large choix de teintes de PVC plaxé",
          "3 couleurs de profil au choix : blanc, brun ou anthracite",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/IGLO EDGE/structure1.png",
        "./assets/Products/Windows/IGLO EDGE/structure2.png",
      ],
    },
    {
      name: "IGLO Energy",
      tagline: "",
      heroVideo: "./assets/Products/Windows/IGLO Energy/hero.mp4",
      specs: {
        soundInsulation: "37-46 dB",
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 0.71 W/(m2K)*",
        numberOfChambers: 7,
        installationDepth: "82 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO Energy",
        detailVideo: "./assets/Products/Windows/IGLO Energy/detail.mp4",
        description:
          "Un profil innovant et original à 7 chambres de classe A, réalisé exclusivement à partir de matériaux vierges. Le premier système au monde utilisant un joint central en EPDM moussé pour garantir les meilleurs paramètres d’efficacité énergétique. Les fenêtres Iglo Energy se distinguent également par leurs excellentes performances en étanchéité à l’eau, micro‑ventilation et résistance au vent.",
        standardEquipment: [
          "Vitrage double chambre Ug = 0,5 W/(m2K)",
          "Intercalaire chaud Swisspacer Ultimate — en option gratuite",
          "4 gâches anti-effraction selon la taille de l’ouvrant et la quincaillerie",
          "Micro-ventilation",
          "Poignée de fenêtre en aluminium",
          "Sécurité de fausse manœuvre",
          "Joints périphériques, de vitrage et central en noir ou gris",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Habillage d’appui",
          "Large choix de teintes de PVC plaxé",
          "Profil disponible en deux couleurs : blanc, brun",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/IGLO Energy/structure1.png",
        "./assets/Products/Windows/IGLO Energy/structure2.png",
      ],
    },
    {
      name: "IGLO Energy Classic",
      tagline: "Les meilleures performances dissimulées dans un design moderne",
      heroVideo: "./assets/Products/Windows/IGLO Energy Classic/hero.mp4",
      specs: {
        soundInsulation: "36-42 dB",
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 0.73 W/(m2K)*",
        numberOfChambers: 7,
        installationDepth: "82 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO Energy Classic",
        detailVideo: "./assets/Products/Windows/IGLO Energy Classic/detail.mp4",
        description:
          "Un design unique avec possibilité de parclose carrée pour s’inscrire dans les dernières tendances architecturales. Les remarquables paramètres d’isolation thermique sont assurés par la structure optimale du profil à 7 chambres, un système d’étanchéité spécialement conçu en EPDM moussé et des vitrages à haute performance thermique.",
        standardEquipment: [
          "Vitrage double chambre Ug = 0,5 W/(m2K)",
          "Intercalaire chaud Swisspacer Ultimate — en option gratuite",
          "Soudure V-Perfect",
          "4 gâches anti-effraction selon la taille de l’ouvrant et la quincaillerie",
          "Micro-ventilation",
          "Poignée de fenêtre en aluminium",
          "Sécurité de fausse manœuvre",
          "Joints périphériques, de vitrage et central en noir ou gris",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Habillage d’appui",
          "Large sélection de couleurs de placage PVC",
        ],
        profileColors: ["blanc", "anthracite", "bronze"],
      },
      structureImages: [
        "./assets/Products/Windows/IGLO Energy Classic/structure1.png",
        "./assets/Products/Windows/IGLO Energy Classic/structure2.png",
      ],
    },
    {
      name: "IGLO ENERGY ALUCOVER",
      tagline: "Redéfinir l'excellence du design",
      heroVideo: "./assets/Products/Windows/IGLO ENERGY ALUCOVER/hero.mp4",
      specs: {
        soundInsulation: "36 - 42 dB*",
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 0,76 W/(m2K)*",
        numberOfChambers: 7,
        installationDepth: "93 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO ENERGY ALUCOVER",
        detailVideo:
          "./assets/Products/Windows/IGLO ENERGY ALUCOVER/detail.mp4",
        description:
          "Découvrez la fusion d’excellentes performances d’isolation thermique et d’un design contemporain avec Iglo Energy Alucover. Libérez votre créativité grâce à une vaste palette de couleurs pour façonner un style unique et personnalisé pour chaque intérieur ou façade.",
        standardEquipment: [
          "Quincaillerie MACO MULTI-MATIC KS avec 4 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation sur oscillo‑battant",
          "Caches‑charnières en 4 couleurs : blanc, argent, brun clair, brun",
          "Poignée de fenêtre Dublin",
          "Triple vitrage (2 chambres) rempli d’argon, Ug = 0,5 W/(m²K)",
          "Intercalaire Swisspacer Ultimate",
          "Parclose rectangulaire",
          "Soudure V‑Perfect",
          "2 joints EPDM (extérieur et intérieur) + 1 joint central en EPDM moussé, joints disponibles en noir",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort d’ouvrant en acier en forme de ‘C’, renfort de cadre en acier 2 mm fermé (plein)",
          "Laque mate RAL",
          "Habillage PVC sous appui 5 chambres avec joint",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/IGLO ENERGY ALUCOVER/structure1.png",
        "./assets/Products/Windows/IGLO ENERGY ALUCOVER/structure2.png",
      ],
    },
    {
      name: "IGLO 5",
      tagline: "Haute qualité à prix attractif",
      heroVideo: "./assets/Products/Windows/IGLO 5/hero.mp4",
      specs: {
        soundInsulation: "36-44 dB",
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0,89 W/(m2K)*",
        numberOfChambers: 5,
        installationDepth: "70 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO 5",
        detailVideo: "./assets/Products/Windows/IGLO 5/detail.mp4",
        description:
          "Un système à 5 chambres offrant de très bons paramètres d’isolation thermique. Notre solution innovante repose sur un profil de classe A blanc neige, réalisé exclusivement à partir de matériaux vierges pour garantir la meilleure qualité. Ces fenêtres conviennent parfaitement aux climats chauds comme froids.",
        standardEquipment: [
          "Quincaillerie MACO MULTI‑MATIC KS avec 2 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation en oscillo‑battant",
          "Caches‑charnières en 4 couleurs : blanc, argent, brun clair, brun",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire en acier galvanisé, ou en option Swisspacer Ultimate",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort acier 1,5 mm pour cadre et ouvrant (2 mm pour l’ouvrant de porte-fenêtre), en forme de ‘c’",
          "Âme du profil en blanc",
          "Habillage PVC sous appui 5 chambres avec joint",
          "Profil disponible en deux couleurs : blanc et brun",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/IGLO 5/structure1.png",
        "./assets/Products/Windows/IGLO 5/structure2.png",
      ],
    },
    {
      name: "IGLO 5 Classic",
      tagline: "Des solutions éprouvées pour la satisfaction des clients",
      heroVideo: "./assets/Products/Windows/IGLO 5 Classic/hero.mp4",
      specs: {
        soundInsulation: "34-42 dB",
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0.83 W/(m²K)*",
        numberOfChambers: 5,
        installationDepth: "70 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO 5 Classic",
        detailVideo: "./assets/Products/Windows/IGLO 5 Classic/detail.mp4",
        description:
          "Des fenêtres appréciées par les clients du monde entier. Elles offrent non seulement de très bons paramètres d’isolation thermique, mais aussi d’excellentes qualités esthétiques. Avec une large gamme de décors Renolit et de nombreuses options, nous créons des fenêtres répondant aux attentes des clients les plus exigeants.",
        standardEquipment: [
          "Quincaillerie MACO MULTI‑MATIC KS avec 2 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation en oscillo‑battant",
          "Caches‑charnières en 4 couleurs : blanc, argent, brun clair, brun",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire en acier galvanisé, en option Swisspacer Ultimate",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort acier 1,5 mm pour cadre et ouvrant (2 mm pour l’ouvrant de porte‑fenêtre), en forme de ‘c’",
          "Âme du profil en blanc",
          "Habillage PVC sous appui 5 chambres avec joint",
          "Le profil est disponible en trois couleurs : blanc, anthracite et bronze",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/IGLO 5 Classic/structure1.png",
        "./assets/Products/Windows/IGLO 5 Classic/structure2.png",
      ],
    },
    {
      name: "IGLO Light",
      tagline: "Encore plus de lumière naturelle",
      heroVideo: "./assets/Products/Windows/IGLO Light/hero.mp4",
      specs: {
        soundInsulation: "34 dB",
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0,88 W/(m2K)*",
        numberOfChambers: 5,
        installationDepth: "70 mm",
        profileClass: null,
      },
      detailSection: {
        title: "IGLO Light",
        tagline: "Encore plus de lumière naturelle",
        detailVideo: "./assets/Products/Windows/IGLO Light/detail.mp4",
        description:
          "Ce système original à 5 chambres se distingue par ses qualités esthétiques et ses profils fins de cadre et d’ouvrant. Par rapport aux systèmes traditionnels, il dispose d’un meneau mobile 32% plus mince pour laisser entrer davantage de lumière naturelle.",
        standardEquipment: [
          "Quincaillerie MACO MULTI‑MATIC KS avec 2 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation en oscillo‑battant",
          "Caches‑charnières en 4 couleurs : blanc, argent, brun clair, brun",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire chaud Swisspacer Ultimate — en option gratuite",
          "Intercalaire en acier galvanisé",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort acier 1,5 mm pour cadre et ouvrant (2 mm pour l’ouvrant de porte‑fenêtre), en forme de ‘c’",
          "Âme du profil en blanc",
          "Habillage PVC sous appui 5 chambres avec joint",
          "Soudure V‑Perfect",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/IGLO Light/structure1.png",
        "./assets/Products/Windows/IGLO Light/structure2.png",
      ],
    },
    {
      name: "IGLO EXT",
      tagline:
        "Fenêtres et portes‑fenêtres PVC modernes s’ouvrant vers l’extérieur",
      heroVideo: "./assets/Products/Windows/Iglo EXT/hero.mp4",
      specs: {
        soundInsulation: "34 - 35 dB*",
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0,89 W/(m²K)*",
        numberOfChambers: 5,
        installationDepth: "70 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO EXT",
        detailVideo: "./assets/Products/Windows/IGLO EXT/detail.mp4",
        description:
          "Les fenêtres et portes‑fenêtres s’ouvrant vers l’extérieur se distinguent par leur design moderne et leurs excellentes performances d’isolation thermique. De série, ces fenêtres disposent de ferrures cachées (invisibles lorsque la fenêtre est fermée), tandis que les portes‑fenêtres sont équipées de ferrures de porte (en applique). Le système Iglo EXT est idéal pour ceux qui recherchent un design contemporain et des qualités esthétiques élevées.",
        standardEquipment: [
          "Vitrage double chambre Ug = 1,1 W/(m²K)",
          "Ferrures cachées MACO Multi‑Power sur la fenêtre (charnières invisibles fenêtre fermée), ferrures de porte pour portes‑fenêtres",
          "Gâche à double galet DM20 pour verrouillage étanche ou avec aération de confort",
          "Poignée aluminium avec insert double face",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire chaud Swisspacer Ultimate — option gratuite",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort cadre et ouvrant en acier 1,5 mm fermé (plein), en ‘c’ (2 mm pour portes‑fenêtres)",
          "Âme du profil en blanc",
          "Habillage PVC sous appui 5 chambres avec joint",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/Iglo EXT/structure1.png",
        "./assets/Products/Windows/Iglo EXT/structure2.png",
      ],
    },
    {
      name: "IGLO PREMIER",
      tagline:
        "Fenêtres oscillo‑battantes modernes à ouverture vers l’extérieur",
      heroVideo: "./assets/Products/Windows/IGLO PREMIER/hero.mp4",
      specs: {
        soundInsulation: "34 - 35 dB*",
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0.89 W/(m²K)*",
        numberOfChambers: 5,
        installationDepth: "70 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO PREMIER",
        detailVideo: "./assets/Products/Windows/IGLO PREMIER/detail.mp4",
        description:
          "Des fenêtres oscillo‑battantes à ouverture extérieure, basées sur un profil 5 chambres de classe A extrêmement performant, fabriqué exclusivement à partir de matériau vierge. Le système est doté d’un double joint et d’une quincaillerie fiable pour garantir des valeurs d’usage élevées pendant de nombreuses années.",
        standardEquipment: [
          "Paumelles à ciseaux (invisibles lorsque la fenêtre est fermée)",
          "Gâche à double galet DM20 pour verrouillage étanche ou avec aération de confort",
          "Vitrage double chambre Ug = 1,1 W/(m²K)",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire chaud Swisspacer Ultimate — en option gratuite",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort cadre et ouvrant en acier 1,5 mm fermé (plein), en ‘c’ (2 mm pour portes‑fenêtres)",
          "Âme du profil en blanc",
          "Habillage PVC sous appui 5 chambres avec joint",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/Iglo Premier/structure1.png",
        "./assets/Products/Windows/Iglo Premier/structure2.png",
      ],
    },
    {
      name: "IDEAL NEO AD",
      tagline: "Plus que du design moderne",
      heroVideo: "./assets/Products/Windows/IDEAL NEO AD/hero.mp4",
      specs: {
        soundInsulation: "36 dB",
        gaskets: "2 joints",
        thermalTransmittance: "Uw = 0.79 W/(m²K)*",
        numberOfChambers: 6,
        installationDepth: "76 mm",
        glassPackages: "24-54 mm",
        profileClass: "B",
      },
      detailSection: {
        title: "IDEAL NEO AD",
        detailVideo: "./assets/Products/Windows/IDEAL NEO AD/detail.mp4",
        description:
          "Des profils fins et symétriques, en phase avec les tendances actuelles, confèrent légèreté et élégance aux fenêtres. Des assemblages très étroits offrent encore plus de lumière dans les pièces. Une solution attractive pour le neuf comme pour la rénovation.",
        standardEquipment: [
          "Vitrage double chambre Ug = 0,5 W/(m²K)",
          "Intercalaire chaud Swisspacer Ultimate — en option gratuite",
          "4 gâches anti‑effraction selon la taille de l’ouvrant et la quincaillerie",
          "Micro‑ventilation",
          "Poignée de fenêtre en aluminium",
          "Sécurité de fausse manœuvre",
          "Joints périphériques et de vitrage en noir ou gris",
          "Remplissage de la gorge inférieure de quincaillerie",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/IDEAL NEO AD/structure1.png",
        "./assets/Products/Windows/IDEAL NEO AD/structure2.png",
      ],
    },
    {
      name: "IDEAL NEO MD",
      tagline: "Plus que du design moderne",
      heroVideo: "./assets/Products/Windows/IDEAL NEO MD/hero.mp4",
      specs: {
        soundInsulation: "36 dB",
        gaskets: "3 joints",
        thermalTransmittance: "Uw = 0.76 W/(m²K)*",
        numberOfChambers: 6,
        installationDepth: "76 mm",
        glassPackages: "24-54 mm",
        profileClass: "B",
      },
      detailSection: {
        title: "IDEAL NEO MD",
        detailVideo: "./assets/Products/Windows/IDEAL NEO MD/detail.mp4",
        description:
          "Des profils fins et symétriques, en accord avec les tendances actuelles, apportent légèreté et élégance aux fenêtres. Des combinaisons de profils extrêmement étroites signifient encore plus de lumière dans les pièces. Une solution attrayante, aussi bien pour le neuf que pour la rénovation.",
        standardEquipment: [
          "Vitrage double chambre Ug = 0,5 W/(m²K)",
          "Intercalaire chaud Swisspacer Ultimate — en option gratuite",
          "4 gâches anti‑effraction selon la taille de l’ouvrant et la quincaillerie",
          "Micro‑ventilation",
          "Poignée de fenêtre en aluminium",
          "Sécurité de fausse manœuvre",
          "Joints périphériques, de vitrage et central en noir ou gris",
          "Remplissage de la gorge inférieure de quincaillerie",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/IDEAL NEO MD/structure1.png",
        "./assets/Products/Windows/IDEAL NEO MD/structure2.png",
      ],
    },
    {
      name: "IDEAL NEO MD-FS",
      tagline: "En harmonie avec l’architecture",
      heroVideo: "./assets/Products/Windows/IDEAL NEO MD-FS/hero.png",
      specs: {
        soundInsulation: "36 dB",
        gaskets: "3 joints",
        thermalTransmittance: "Uw = 0.73 W/(m²K)*",
        numberOfChambers: 6,
        installationDepth: "76 mm",
        glassPackages: "36-68 mm",
        profileClass: null,
      },
      detailSection: {
        title: "IDEAL NEO MD-FS",
        detailVideo: "./assets/Products/Windows/IDEAL NEO MD-FS/detail.png",
        description:
          "IDEAL NEO MD‑FS est une proposition de design particulièrement attractive pour les clients qui apprécient le style intemporel. Une forme simple, symétrique et cubiste caractérise le système : des angles vifs, une architecture géométrique et, en même temps, une grande légèreté visuelle.",
        standardEquipment: [
          "Vitrage double chambre Ug = 0,5 W/(m²K)",
          "Intercalaire chaud Swisspacer Ultimate — en option gratuite",
          "4 gâches anti‑effraction selon la taille de l’ouvrant et la quincaillerie",
          "Micro‑ventilation",
          "Poignée de fenêtre en aluminium",
          "Sécurité de fausse manœuvre",
          "Joints périphériques, de vitrage et central en noir ou gris",
          "Remplissage de la gorge inférieure de quincaillerie",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/IDEAL NEO MD-FS/structure1.png",
        "./assets/Products/Windows/IDEAL NEO MD-FS/structure2.png",
      ],
    },
    {
      name: "IDEAL NEO MD MONOBLOCK",
      tagline: null,
      heroVideo: "./assets/Products/Windows/IDEAL NEO MD MONOBLOCK/hero.png",
      specs: {
        soundInsulation: "36 dB",
        gaskets: "3 joints",
        thermalTransmittance: "Uw = 0.76 W/(m²K)*",
        numberOfChambers: 6,
        installationDepth: "76 mm / 122 mm / 142 mm / 162 mm",
        glassPackages: "24-52 mm",
        profileClass: null,
      },
      detailSection: {
        title: "IDEAL NEO MD MONOBLOCK",
        detailVideo:
          "./assets/Products/Windows/IDEAL NEO MD MONOBLOCK/detail.png",
        description:
          "Les cadres monobloc sont conçus pour le montage de fenêtres au sein de la couche d’isolation. La vaste gamme de dimensions (76 mm, 122 mm, 142 mm, 162 mm) permet un choix adapté à l’épaisseur de l’isolant. Une tablette spéciale (appui de fenêtre) située côté extérieur du cadre couvre esthétiquement l’isolation autour du pourtour, évitant les ponts thermiques. La feuillure intérieure du cadre monobloc garantit une pose soignée depuis l’intérieur, sans besoin d’enduit.",
        standardEquipment: [],
      },
      structureImages: [
        "./assets/Products/Windows/IDEAL NEO MD MONOBLOCK/structure1.png",
        "./assets/Products/Windows/IDEAL NEO MD MONOBLOCK/structure2.png",
      ],
    },
    {
      name: "IDEAL NEO MD RENOVATION",
      tagline: null,
      heroVideo: "./assets/Products/Windows/IDEAL NEO MD RENOVATION/hero.png",
      specs: {
        soundInsulation: "36 dB",
        gaskets: "3 joints",
        thermalTransmittance: "Uw = 0.76 W/(m²K)*",
        numberOfChambers: "5/6",
        installationDepth: "76 mm",
        glassPackages: "24-52 mm",
        profileClass: null,
      },
      detailSection: {
        title: "IDEAL NEO MD RENOVATION",
        detailVideo:
          "./assets/Products/Windows/IDEAL NEO MD RENOVATION/detail.png",
        description:
          "Le système de cadre de rénovation est conçu pour la pose de fenêtres sans démontage des anciens cadres. Cette solution utilise des cadres de rénovation spéciaux avec un profil de recouvrement englobant l’ancien cadre bois, créant une bande intérieure propre. À l’extérieur, des profils de coffrage spécifiques peuvent être appliqués. Les profils de recouvrement existent en différentes largeurs (40 mm, 70 mm) et peuvent être recoupés selon les besoins du chantier.",
        standardEquipment: [],
      },
      structureImages: [
        "./assets/Products/Windows/IDEAL NEO MD RENOVATION/structure1.png",
        "./assets/Products/Windows/IDEAL NEO MD RENOVATION/structure2.png",
      ],
    },
    {
      name: "IDEAL 7000 NL",
      tagline: "En harmonie avec l’architecture",
      heroVideo: "./assets/Products/Windows/IDEAL 7000 NL/hero.png",
      specs: {
        soundInsulation: "36 dB",
        gaskets: "2 joints",
        thermalTransmittance: "Uw = 0.82 W/(m²K)*",
        numberOfChambers: 5,
        installationDepth: "120 mm",
        glassPackages: "24-54 mm",
        profileClass: null,
      },
      detailSection: {
        title: "IDEAL 7000 NL",
        detailVideo: "./assets/Products/Windows/IDEAL 7000 NL/detail.mp4",
        description:
          "Le système IDEAL 7000 NL est la solution idéale pour le marché néerlandais. Son cadre de 120 mm de large avec feuillures extérieures permet une installation facile, rapide et esthétique des fenêtres dans les bâtiments en brique de parement (clinker), sans travaux de maçonnerie supplémentaires.",
        standardEquipment: [
          "Vitrage 24 mm, Ug = 1,1 W/(m²K)",
          "Intercalaire chaud Swisspacer Ultimate — en option gratuite",
          "4 gâches anti‑effraction selon la taille de l’ouvrant et la quincaillerie",
          "Micro‑ventilation",
          "Poignée de fenêtre en aluminium — Hoppe",
          "Sécurité de fausse manœuvre",
          "Joints périphériques et de vitrage en noir ou gris",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Profil disponible en 3 couleurs : blanc, anthracite, crème",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/IDEAL 7000 NL/structure1.png",
        "./assets/Products/Windows/IDEAL 7000 NL/structure2.png",
      ],
    },
    {
      name: "MB-86N SI",
      tagline: "Excellents paramètres et durabilité de l’aluminium",
      heroVideo: "./assets/Products/Windows/MB-86N SI/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0.76 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "77 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-86N SI",
        detailVideo: "./assets/Products/Windows/MB-86N SI/detail.mp4",
        description:
          "Les fenêtres aluminium MB‑86N SI se distinguent par d’excellents paramètres d’isolation thermique et un design moderne. Avec plus de 200 couleurs au choix et de nombreuses options, elles offrent une personnalisation complète et peuvent être équipées de solutions Smart Home pour plus de confort.",
        standardEquipment: [
          "Quincaillerie MACO MULTI‑MATIC KS avec 2 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation en oscillo‑battant",
          "Caches‑charnières en 3 couleurs : blanc, argent, brun",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "1 joint EPDM + 1 joint central en EPDM moussé, joints disponibles en noir",
          "Couleurs mates RAL : blanc (9016), anthracite (7016)",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/MB-86N SI/structure1.png",
        "./assets/Products/Windows/MB-86N SI/structure2.png",
      ],
    },
    {
      name: "MB-79N SI",
      tagline: "Choisissez l’efficacité énergétique",
      heroVideo: "./assets/Products/Windows/MB-79N SI/hero.png",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0.81 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "70 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-79N SI",
        detailVideo: "./assets/Products/Windows/MB-79N SI/detail.mp4",
        description:
          "La nouvelle gamme de fenêtres aluminium à isolation thermique renforcée, dotées d’inserts isolants et d’un joint central bi‑composant, garantit des factures de chauffage réduites. Son design moderne, avec plus de 200 couleurs et de nombreuses options, en fait un choix idéal pour les clients exigeants.",
        standardEquipment: [
          "Quincaillerie MACO MULTI‑MATIC KS avec 2 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation en oscillo‑battant",
          "Caches‑charnières en 3 couleurs : blanc, argent, brun",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "1 joint EPDM + 1 joint central en EPDM moussé, joints disponibles en noir",
          "Couleurs mates RAL : blanc (9016), anthracite (7016)",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/MB-79N SI/structure1.png",
        "./assets/Products/Windows/MB-79N SI/structure2.png",
      ],
    },
    {
      name: "MB-70HI",
      tagline: "Fenêtres aluminium légères et durables pour un confort durable",
      heroVideo: "./assets/Products/Windows/MB-70HI/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 0.96 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "70 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-70HI",
        detailVideo: "./assets/Products/Windows/MB-70HI/detail.mp4",
        description:
          "Les fenêtres aluminium réalisées avec ce système peuvent être utilisées aussi bien dans les bâtiments individuels que dans les façades en aluminium. La construction légère et durable garantit un haut niveau de confort pendant de nombreuses années.",
        standardEquipment: [
          "Quincaillerie MACO MULTI‑MATIC KS avec 2 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation en oscillo‑battant",
          "Caches‑charnières en 3 couleurs : blanc, argent, brun",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "1 joint EPDM + 1 joint central en EPDM moussé, joints disponibles en noir",
          "Couleurs mates RAL : blanc (9016), anthracite (7016)",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/MB-70HI/structure1.png",
        "./assets/Products/Windows/MB-70HI/structure2.png",
      ],
    },
    {
      name: "MB-70",
      tagline:
        "Système aluminium moderne à excellente isolation thermique et acoustique",
      heroVideo: "./assets/Products/Windows/MB-70/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 1.06 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "70 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-70",
        detailVideo: "./assets/Products/Windows/MB-70/detail.mp4",
        description:
          "Le système MB‑70 est une solution aluminium moderne conçue pour la fabrication d’éléments architecturaux extérieurs nécessitant une isolation thermique et acoustique. Il offre durabilité, performances et design élégant adaptés à divers styles de bâtiments.",
        standardEquipment: [
          "Quincaillerie MACO MULTI‑MATIC KS avec 2 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation en oscillo‑battant",
          "Caches‑charnières en 3 couleurs : blanc, argent, brun",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "1 joint EPDM + 1 joint central en EPDM moussé, joints disponibles en noir",
          "Couleurs mates RAL : blanc (9016), anthracite (7016)",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/MB-70/structure1.png",
        "./assets/Products/Windows/MB-70/structure2.png",
      ],
    },
    {
      name: "MB-45",
      tagline:
        "Système aluminium moderne pour des aménagements intérieurs polyvalents",
      heroVideo: "./assets/Products/Windows/MB-45/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: null,
        numberOfChambers: 2,
        installationDepth: "45 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-45",
        detailVideo: "./assets/Products/Windows/MB-45/detail.mp4",
        description:
          "Le système de fenêtres aluminium MB‑45 permet de réaliser des aménagements intérieurs variés. Il allie durabilité et esthétique moderne, idéal pour les projets recherchant une finition soignée sans nécessité d’isolation thermique.",
        standardEquipment: [
          "Quincaillerie MACO MULTI‑MATIC KS avec 2 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation en oscillo‑battant",
          "Caches‑charnières en 3 couleurs : blanc, argent, brun",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "2 joints EPDM disponibles en noir",
          "Couleurs mates RAL : blanc (9016), anthracite (7016)",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/MB-45/structure1.png",
        "./assets/Products/Windows/MB-45/structure2.png",
      ],
    },
    {
      name: "SOFTLINE - 68, 78, 88",
      tagline: "Durabilité et beauté de la nature",
      heroVideo: "./assets/Products/Windows/SOFTLINE - 68, 78, 88/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "68 Uw = 1.08* / 78 Uw = 0.9** / 88 Uw = 0.8***",
        numberOfChambers: null,
        installationDepth: "68/78/88 mm",
        profileClass: null,
      },
      detailSection: {
        title: "SOFTLINE - 68, 78, 88",
        detailVideo:
          "./assets/Products/Windows/SOFTLINE - 68, 78, 88/detail.mp4",
        description:
          "Nos fenêtres en bois allient la plus haute qualité de fabrication, des matériaux écologiques et une élégance classique. Une durabilité exceptionnelle est assurée grâce à une parclose aluminium qui protège le bois des UV et de l’humidité. La série Softline se caractérise par des profils joliment arrondis aux surfaces lisses et brillantes, disponibles en pin et en méranti.",
        standardEquipment: [
          "Quincaillerie MACO MULTI‑MATIC KS avec 2 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation en oscillo‑battant",
          "Caches‑charnières en 3 couleurs : blanc, argent, brun",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "Bavette d’évacuation d’eau",
          "2 joints EPDM",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/SOFTLINE - 68, 78, 88/structure1.png",
        "./assets/Products/Windows/SOFTLINE - 68, 78, 88/structure2.png",
      ],
    },
    {
      name: "DUOLINE - 68, 78, 88",
      tagline: "Alliance unique du bois et de l’aluminium",
      heroVideo: "./assets/Products/Windows/DUOLINE - 68, 78, 88/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints",
        thermalTransmittance: "68 Uw = 0.90* / 78 Uw = 0.84** / 88 Uw = 0.79**",
        numberOfChambers: null,
        installationDepth: "68/78/88 mm + spacer bar 14 mm",
        profileClass: null,
      },
      detailSection: {
        title: "DUOLINE - 68, 78, 88",
        detailVideo:
          "./assets/Products/Windows/DUOLINE - 68, 78, 88/detail.mp4",
        description:
          "Les fenêtres DUOLINE associent la beauté intemporelle du bois naturel à la durabilité moderne de l’aluminium. Cette structure hybride unique assure une excellente isolation, des performances durables et une esthétique élégante. De nombreuses options de personnalisation permettent d’adapter parfaitement les fenêtres à vos besoins architecturaux et personnels.",
        standardEquipment: [
          "Quincaillerie MACO MULTI‑MATIC KS avec 2 gâches anti‑effraction et revêtement anticorrosion Silber‑Look pour une protection durable et un fonctionnement fluide",
          "Lève‑ouvrant (sécurité de fausse manœuvre — selon la hauteur de la fenêtre)",
          "Micro‑ventilation en oscillo‑battant",
          "Caches‑charnières en 3 couleurs : blanc, argent, brun",
          "Poignée en aluminium",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "Bavette d’évacuation d’eau",
          "3 joints EPDM",
        ],
      },
      structureImages: [
        "./assets/Products/Windows/DUOLINE - 68, 78, 88/structure1.png",
        "./assets/Products/Windows/DUOLINE - 68, 78, 88/structure2.png",
      ],
    },
  ],
  doors: [
    // Doors
    {
      name: "Iglo Energy",
      tagline:
        "Porte d’entrée PVC moderne au design de pointe et aux excellents paramètres",
      heroVideo: "./assets/Products/Doors/Iglo Energy/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Ud = 0.8 W/(m²K)*",
        numberOfChambers: 7,
        installationDepth: "82 mm",
        profileClass: null,
      },
      detailSection: {
        title: "Iglo Energy",
        detailVideo: "./assets/Products/Doors/Iglo Energy/detail.mp4",
        description:
          "La porte d’entrée extérieure Iglo Energy en PVC offre un design moderne et élégant, combiné à une haute efficacité énergétique et une fonctionnalité optimale. Son excellente isolation thermique est assurée par des matériaux de qualité et un seuil spécialement conçu avec rupteur de pont thermique, améliorant les performances et le confort du système.",
        standardEquipment: [
          "Serrure à crémone 3 points",
          "3 paumelles à deux vantaux",
          "Vitrage double Ug = 1,1 W/(m²K)",
          "Seuil avec rupteur thermique pour une meilleure isolation",
          "Poignée en aluminium",
          "Insert de montage",
        ],
      },
      structureImages: [],
    },
    {
      name: "Iglo 5",
      tagline: "Haute qualité à un prix attractif",
      heroVideo: "./assets/Products/Doors/Iglo 5/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Ud = 1.0 W/(m²K)*",
        numberOfChambers: 5,
        installationDepth: "70 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "Iglo 5",
        detailVideo: "./assets/Products/Doors/Iglo 5/detail.mp4",
        description:
          "Le système Iglo 5 se caractérise par une structure à 5 chambres offrant une très bonne isolation thermique à un prix attractif. Réalisées à partir d’un profil de classe A blanc neige composé exclusivement de matériaux vierges, ces portes garantissent une haute qualité et une grande fiabilité. Conçu pour les climats chauds comme froids, Iglo 5 allie durabilité, fonctionnalité et esthétique.",
        standardEquipment: [
          "Serrure à crémone 3 points",
          "3 paumelles à deux vantaux",
          "Vitrage double Ug = 1,1 W/(m²K)",
          "Seuil avec rupteur thermique pour une meilleure isolation",
          "Poignée en aluminium",
          "Insert de montage",
        ],
      },
      structureImages: [],
    },
    {
      name: "Iglo Edge",
      tagline: "Design de pointe et excellents paramètres",
      heroVideo: "./assets/Products/Doors/Iglo Edge/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Ud = 0.81 W/(m²K)*",
        numberOfChambers: 7,
        installationDepth: "82 mm",
        profileClass: null,
      },
      detailSection: {
        title: "Iglo Edge",
        detailVideo: "./assets/Products/Doors/Iglo Edge/detail.mp4",
        description:
          "La porte d’entrée Iglo Edge est un design propriétaire qui associe une technologie innovante à une esthétique moderne et épurée, inspirée des tendances actuelles. Fabriquée à partir de matériaux de construction de haute qualité, elle offre une isolation thermique remarquable et des performances durables. Un équilibre parfait entre élégance et fonctionnalité pour satisfaire les utilisateurs les plus exigeants.",
        standardEquipment: [
          "Serrure à crémone 3 points",
          "3 paumelles à deux vantaux",
          "Triple vitrage Ug = 0,5 W/(m²K)",
          "Seuil avec rupteur thermique pour une isolation supérieure",
          "Poignée en aluminium",
          "Insert de montage",
        ],
      },
      structureImages: [],
    },
    {
      name: "D-ART Line",
      tagline: "Alliance parfaite entre art et technologie moderne",
      heroVideo: "./assets/Products/Doors/D-ART Line/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Ud = 0.83 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "77 mm",
        profileClass: null,
      },
      detailSection: {
        title: "D-ART Line",
        detailVideo: "./assets/Products/Doors/D-ART Line/detail.mp4",
        description:
          "Les portes D‑ART Line associent technologie moderne et design artistique, offrant style et performance. Efficaces sur le plan énergétique, elles disposent d’une construction durable résistante aux intempéries et assurent une excellente isolation thermique et acoustique pour un confort et une sécurité maximum. Un choix parfait pour ceux qui privilégient l’esthétique, la durabilité et l’élégance.",
        standardEquipment: [
          "Serrure à crémone 3 points",
          "Paumelles invisibles",
          "Insert isolant",
          "Seuil avec rupteur thermique pour une meilleure isolation",
          "Poignée en aluminium",
          "Insert de montage",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-86N SI",
      tagline: "Réduisez vos factures de chauffage",
      heroVideo: "./assets/Products/Doors/MB-86N SI/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Ud = 0.83 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "77 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-86N SI",
        detailVideo: "./assets/Products/Doors/MB-86N SI/detail.mp4",
        description:
          "La porte extérieure en aluminium MB‑86N SI offre une durabilité exceptionnelle et une isolation thermique supérieure, idéale pour les bâtiments à haute efficacité énergétique. Équipé d’un seuil aluminium avec rupteur thermique, ce système allie élégance et performance tout en contribuant à réduire les coûts de chauffage et à améliorer le confort intérieur.",
        standardEquipment: [
          "Serrure à crémone 3 points",
          "3 paumelles à deux vantaux",
          "Paumelles invisibles pour panneau affleurant des deux côtés",
          "Vitrage double Ug = 1,1 W/(m²K)",
          "Insert isolant",
          "Finition laquée mate RAL 7016 et 9016",
          "Seuil avec rupteur thermique pour une meilleure isolation",
          "Poignée en aluminium",
          "Insert de montage",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-79N SI+",
      tagline: "La dernière technologie chez vous",
      heroVideo: "./assets/Products/Doors/MB-79N SI+/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Ud = 0.85 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "70 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-79N SI+",
        detailVideo: "./assets/Products/Doors/MB-79N SI+/detail.mp4",
        description:
          "Le système de porte aluminium MB‑79N SI+ est conçu pour des portes à un ou deux vantaux répondant à des exigences thermiques et acoustiques renforcées. Sa structure avancée et son triple joint, incluant un seuil avec rupteur thermique, assurent une excellente isolation et une grande durabilité. Une porte alliant design moderne, performances fiables et efficacité énergétique.",
        standardEquipment: [
          "Serrure à crémone 3 points",
          "3 paumelles à deux vantaux",
          "Vitrage double Ug = 1,1 W/(m²K)",
          "Insert isolant",
          "Seuil avec rupteur thermique pour une meilleure isolation",
          "Poignée en aluminium",
          "Insert de montage",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-70HI",
      tagline: "Profitez de la perfection pendant de nombreuses années",
      heroVideo: "./assets/Products/Doors/MB-70HI/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 1.2 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "70 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-70HI",
        detailVideo: "./assets/Products/Doors/MB-70HI/detail.webm",
        description:
          "Le système de porte aluminium MB‑70HI offre d’excellentes performances d’isolation thermique à un prix attractif. Conçues pour la durabilité et le confort, ces portes résistent aux conditions climatiques variées tout en conservant leur élégance. MB‑70HI allie qualité, efficacité énergétique et design intemporel pour une satisfaction durable.",
        standardEquipment: [
          "Serrure à crémone 3 points",
          "3 paumelles à deux vantaux",
          "Vitrage double Ug = 1,1 W/(m²K)",
          "Finition laquée mate RAL 7016 et 9016",
          "Seuil avec rupteur thermique pour une meilleure isolation",
          "Poignée en aluminium",
          "Insert de montage",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-70",
      tagline: "Solution pour les clients exigeants",
      heroVideo: "./assets/Products/Doors/MB-70/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 1.3 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "70 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-70",
        detailVideo: "./assets/Products/Doors/MB-70/detail.mp4",
        description:
          "Le système de porte extérieure en aluminium MB‑70 s’adresse aux clients attachés à la durabilité, à l’efficacité énergétique et au confort. Basé sur des solutions technologiques éprouvées, il assure une excellente isolation thermique et des performances durables, idéal pour l’architecture moderne et toutes les conditions météorologiques.",
        standardEquipment: [
          "Serrure à crémone 3 points",
          "3 paumelles à deux vantaux",
          "Vitrage double Ug = 1,1 W/(m²K)",
          "Finition laquée mate RAL 7016 et 9016",
          "Seuil avec rupteur thermique pour une meilleure isolation",
          "Poignée en aluminium",
          "Insert de montage",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-45",
      tagline: "Système conçu pour l’intérieur",
      heroVideo: "./assets/Products/Doors/MB-45/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: null,
        numberOfChambers: 1,
        installationDepth: "45 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-45",
        detailVideo: "./assets/Products/Doors/MB-45/detail.mp4",
        description:
          "Le système de porte aluminium MB‑45 est conçu pour l’intérieur, idéal pour les espaces ne nécessitant pas une isolation thermique élevée tels que cloisons, vestibules, vitrines, guichets ou présentoirs. Son profil mono‑chambre sans rupture de pont thermique offre durabilité, fonctionnalité et esthétique épurée, parfait pour l’architecture intérieure.",
        standardEquipment: [
          "Serrure à crémone 3 points",
          "3 paumelles à deux vantaux",
          "Finition laquée mate RAL 7016 et 9016",
          "Seuil",
          "Poignée en aluminium",
          "Insert de montage",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-78EI Fire-Doors",
      tagline: "Sécurité et durabilité avec protection incendie",
      heroVideo: "./assets/Products/Doors/MB-78EI/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Ud = 1,6 W/(m2K)*",
        numberOfChambers: 3,
        installationDepth: "78 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-78EI Fire-Doors",
        detailVideo: "./assets/Products/Doors/MB-78EI/detail.mp4",
        description:
          "Le système de portes coupe‑feu MB‑78EI de Drutex est une solution technologiquement avancée offrant une excellente résistance au feu, étanchéité et isolation. Avec une classe de résistance au feu allant de EI30 à EI60, ces portes garantissent une sécurité maximale tout en conservant esthétique et durabilité. Construites avec des profils aluminium stables dotés de ruptures de pont thermique profilées, les portes MB‑78EI assurent une fiabilité même en conditions extrêmes.",
        standardEquipment: [
          "Profils aluminium isolés thermiquement, profondeur 78 mm",
          "Vitrage coupe‑feu avec multiples options",
          "Quincaillerie conforme aux normes coupe‑feu",
          "Joints spéciaux gonflants et céramiques pour bloquer fumée et feu",
          "Large gamme de couleurs RAL, teintes spéciales et textures",
          "Épaisseurs de remplissage vitrage : 20–45 mm et 47–49 mm",
        ],
      },
      structureImages: [],
    },
    {
      name: "PIVOT",
      tagline: "Portes extérieures à pivot déporté",
      heroVideo: "./assets/Products/Doors/PIVOT/hero.PNG",
      specs: {
        soundInsulation: null,
        gaskets: null,
        thermalTransmittance: null,
        numberOfChambers: null,
        installationDepth: "77 mm",
        profileClass: null,
      },
      detailSection: {
        title: "PIVOT",
        detailVideo: "./assets/Products/Doors/PIVOT/detail.mp4",
        description:
          "La porte PIVOT est un système extérieur spectaculaire conçu pour de grandes entrées, avec un axe de pivot déporté offrant une apparence audacieuse et moderne. Ces portes disposent de paumelles cachées à capacité de charge exceptionnelle, assurant stabilité et fluidité de mouvement même avec des panneaux de grande taille. Parfaites pour les architectures contemporaines, les portes PIVOT allient robustesse, élégance et innovation.",
        standardEquipment: [
          "Axe de pivot déporté pour un design et une fonctionnalité uniques",
          "Paumelles cachées haute capacité",
          "Construction en aluminium durable",
          "Compatible avec les styles architecturaux modernes",
          "Disponible en plusieurs couleurs et finitions RAL",
        ],
      },
      structureImages: [],
    },
    {
      name: "SOFTLINE 68, 78, 88",
      tagline: "Beauté intemporelle du bois",
      heroVideo: "./assets/Products/Doors/SOFTLINE/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints",
        thermalTransmittance:
          "68 Ud = 1,1 W/(m2K)* / 78 Ud = 0,9 W/(m2K)** / 88 Ud = 0,85 W/(m2K)***",
        numberOfChambers: null,
        installationDepth: "68 / 78 / 88 mm",
        profileClass: "Profil en bois lamellé 3 couches",
      },
      detailSection: {
        title: "SOFTLINE 68, 78, 88",
        detailVideo: "./assets/Products/Doors/SOFTLINE/detail.mp4",
        description:
          "Les portes en bois SOFTLINE 68, 78 et 88 incarnent l’élégance intemporelle de l’artisanat du bois. Construites en bois lamellé 3 couches de la plus haute qualité, elles offrent une résistance, une stabilité et une isolation exceptionnelles. Leur esthétique classique se marie harmonieusement aux architectures modernes comme traditionnelles, tandis que le seuil aluminium avec rupteur thermique améliore l’efficacité énergétique du système.",
        standardEquipment: [
          "Crémone 3 points",
          "3 paumelles à rouleaux",
          "3 joints",
          "Vitrage Ug de 0,5 à 1,1 W/(m2K)",
          "Seuil avec rupteur thermique",
          "Finitions peinture lasure et opaque",
          "Poignée en aluminium",
          "Insert de montage",
        ],
      },
      structureImages: [],
    },
  ],
  terraceSystems: [
    // Terrace Systems
    {
      name: "IGLO-HS",
      tagline: "La perfection dans chaque détail",
      heroVideo: "./assets/Products/TerraceSystems/IGLO-HS/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 0.71 W/(m²K)*",
        numberOfChambers: 7,
        installationDepth: "194 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO-HS",
        detailVideo: "./assets/Products/TerraceSystems/IGLO-HS/detail.mp4",
        description:
          "Le système de terrasse IGLO‑HS est la solution idéale pour créer de grandes baies vitrées élégantes qui apportent lumière et espace à votre intérieur. Conçu pour l’architecture moderne, il allie esthétique remarquable et excellente efficacité thermique. Sa structure ultra‑robuste supporte des vantaux jusqu’à 400 kg et un seuil bas intégrable au sol, garantissant confort maximal, fluidité de manœuvre et fonctionnalité.",
        standardEquipment: [
          "Ferrures G‑U relevage‑coulissant avec 3 points de verrouillage",
          "Gâche de micro‑aération",
          "Poignée aluminium intérieure, prise encastrée extérieure",
          "Triple vitrage (2 chambres) rempli d’argon, Ug = 0,5 W/(m²K)",
          "Intercalaire chaud Swisspacer Ultimate — en option gratuite",
          "Joint intérieur velours, joints EPDM et brosse extérieurs en noir",
          "Renfort de cadre en sections aluminium haute qualité avec ruptures thermiques",
          "Renfort d’ouvrant : haut et vertical — acier plein (fermé) 2 mm ; bas — acier en U 3 mm",
          "Âme du profil en blanc",
          "Chariots système d’une capacité de 300 kg",
          "Seuil bas PVC avec renfort et couvre‑seuil aluminium",
        ],
      },
      structureImages: [],
    },
    {
      name: "IGLO-HS ALUCOVER",
      tagline: "Redéfinir l’excellence du design",
      heroVideo: "./assets/Products/TerraceSystems/IGLO-HS ALUCOVER/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0.73 W/(m²K)*",
        numberOfChambers: 7,
        installationDepth: "206 mm",
        profileClass: null,
      },
      detailSection: {
        title: "IGLO-HS ALUCOVER",
        detailVideo:
          "./assets/Products/TerraceSystems/IGLO-HS ALUCOVER/detail.mp4",
        description:
          "Le système de terrasse IGLO‑HS ALUCOVER associe l’isolation supérieure du PVC à la durabilité et à la finition élégante de l’aluminium. Il redéfinit la polyvalence du design, avec une personnalisation sans limite grâce à un large choix de couleurs et de finitions, pour s’accorder à tous les styles architecturaux. Parfait pour créer de grandes surfaces vitrées panoramiques conjuguant beauté, performance et confort.",
        standardEquipment: [
          "Intercalaire Swisspacer Ultimate",
          "Parclose rectangulaire",
          "Poignée en aluminium",
          "Soudure V‑Perfect",
          "Laque mate RAL",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-77HS HI",
      tagline: "Créez votre espace",
      heroVideo: "./assets/Products/TerraceSystems/MB-77HS HI/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 1.0 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "174 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-77HS HI",
        detailVideo: "./assets/Products/TerraceSystems/MB-77HS HI/detail.mp4",
        description:
          "Le système de terrasse aluminium MB‑77HS HI est la solution idéale pour créer de grandes baies vitrées élégantes qui ouvrent l’intérieur sur l’extérieur. Sa structure durable supporte des vantaux jusqu’à 400 kg, tandis que le seuil aluminium bas peut être intégré au sol pour un accès aisé et une esthétique moderne. Il offre un design remarquable et d’excellentes performances thermiques.",
        standardEquipment: [
          "Ferrures G‑U relevage‑coulissant avec 3 points de verrouillage",
          "Gâche de micro‑aération",
          "Poignée aluminium intérieure, prise encastrée extérieure",
          "Triple vitrage (2 chambres) rempli d’argon, Ug = 0,5 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Chariots système d’une capacité de 300 kg",
          "Seuil de 48 mm de hauteur",
          "Couleurs mates RAL : blanc (9016), anthracite (7016)",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-77HS HI MONORAIL",
      tagline: "Créez votre espace",
      heroVideo:
        "./assets/Products/TerraceSystems/MB-77HS HI MONORAIL/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0.75 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "174 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-77HS HI MONORAIL",
        detailVideo:
          "./assets/Products/TerraceSystems/MB-77HS HI MONORAIL/detail.mp4",
        description:
          "Le système de porte ‘Lift & Slide’ MB‑77HS HI MONORAIL est la solution idéale pour relier harmonieusement les espaces intérieurs ou vérandas aux terrasses, balcons ou jardins. Alliant grande durabilité, efficacité thermique et douceur de manœuvre, cette version monorail offre un design épuré et un coulissement aisé pour de larges surfaces vitrées inondant l’intérieur de lumière naturelle.",
        standardEquipment: [
          "Ferrures G‑U relevage‑coulissant avec 3 points de verrouillage",
          "Gâche de micro‑aération",
          "Poignée aluminium intérieure, prise encastrée extérieure",
          "Triple vitrage (2 chambres) rempli d’argon, Ug = 0,5 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Chariots système d’une capacité de 300 kg",
          "Seuil de 48 mm de hauteur",
          "Couleurs mates RAL : blanc (9016), anthracite (7016)",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-59HS HI",
      tagline: "Une esthétique revisitée",
      heroVideo: "./assets/Products/TerraceSystems/MB-59HS HI/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 1.5 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "120 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-59HS HI",
        detailVideo: "./assets/Products/TerraceSystems/MB-59HS HI/detail.mp4",
        description:
          "Le système Lift & Slide MB‑59HS HI est une solution idéale pour relier les espaces de vie, jardins d’hiver et extérieurs tels que terrasses ou balcons. Conçu pour un confort et une fonctionnalité maximum, il offre une manœuvre fluide, un design élégant et une excellente isolation thermique. Parfait pour créer des intérieurs lumineux et spacieux avec un accès facile vers l’extérieur.",
        standardEquipment: [
          "Ferrures G‑U relevage‑coulissant avec 3 points de verrouillage",
          "Gâche de micro‑aération",
          "Poignée aluminium intérieure, prise encastrée extérieure",
          "Triple vitrage (2 chambres) rempli d’argon, Ug = 0,5 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Chariots système d’une capacité de 300 kg",
          "Seuil de 48 mm de hauteur",
          "Couleurs mates RAL : blanc (9016), anthracite (7016)",
        ],
      },
      structureImages: [],
    },
    {
      name: "SOFTLINE HS",
      tagline: "Force et beauté de la nature",
      heroVideo: "./assets/Products/TerraceSystems/SOFTLINE HS/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "from Ug = 0.5 W/(m²K)",
        numberOfChambers: null,
        installationDepth: "164/184/204 mm",
        profileClass: null,
      },
      detailSection: {
        title: "SOFTLINE HS",
        detailVideo: "./assets/Products/TerraceSystems/SOFTLINE HS/detail.mp4",
        description:
          "Le système de porte‑fenêtre en bois SOFTLINE HS, à relevage‑coulissant, est conçu pour de grands vitrages afin d’inonder les intérieurs de lumière naturelle. Des technologies de fabrication avancées garantissent esthétique, durabilité et confort exceptionnels. Il combine harmonieusement la beauté intemporelle du bois avec un design et des performances modernes.",
        standardEquipment: [
          "2 joints EPDM",
          "Profils en bois lamellé de haute qualité disponibles en plusieurs profondeurs (164/184/204 mm)",
          "Excellente isolation thermique du vitrage à partir de Ug = 0,5 W/(m²K)",
          "Manœuvre relevage‑coulissant fluide et silencieuse",
          "Seuil aluminium durable avec rupteur thermique",
          "Large gamme de finitions (lasures et opaques)",
          "Habillage aluminium en option pour une protection accrue",
        ],
      },
      structureImages: [],
    },
    {
      name: "DUOLINE HS",
      tagline: "Classique et moderne",
      heroVideo: "./assets/Products/TerraceSystems/DUOLINE HS/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints EPDM",
        thermalTransmittance: "from Ug = 0.5 W/(m²K)",
        numberOfChambers: null,
        installationDepth: "194/214/234 mm",
        profileClass: null,
      },
      detailSection: {
        title: "DUOLINE HS",
        detailVideo: "./assets/Products/TerraceSystems/DUOLINE HS/detail.mp4",
        description:
          "Le système de porte relevage‑coulissant DUOLINE HS allie la beauté naturelle du bois à la durabilité et à la polyvalence de l’aluminium. Une solution élégante et économe en énergie pour les grands vitrages, garantissant une abondante lumière naturelle et une esthétique raffinée pour les intérieurs modernes.",
        standardEquipment: [
          "3 joints EPDM pour une étanchéité et une isolation optimales",
          "Profils bois de haute qualité avec habillage aluminium",
          "Excellente isolation thermique du vitrage à partir de Ug = 0,5 W/(m²K)",
          "Mécanisme relevage‑coulissant fluide pour une utilisation aisée",
          "Seuil aluminium durable avec rupteur thermique",
          "Large palette de plus de 200 couleurs RAL pour l’extérieur aluminium",
          "Douzaines de finitions opaques et lasures pour l’intérieur bois",
          "Finitions de poignées décoratives et personnalisées en option",
        ],
      },
      structureImages: [],
    },
    {
      name: "IGLO EDGE SLIDE",
      tagline: "Une technologie qui impressionne",
      heroVideo: "./assets/Products/TerraceSystems/IGLO EDGE SLIDE/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 0.65 W/(m²K)*",
        numberOfChambers: 6,
        installationDepth: "163 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO EDGE SLIDE",
        detailVideo:
          "./assets/Products/TerraceSystems/IGLO EDGE SLIDE/detail.mp4",
        description:
          "Le système IGLO EDGE SLIDE représente la nouvelle génération de portes coulissantes de terrasse. Il combine un design angulaire moderne et une technologie PVC de pointe pour des performances thermiques remarquables et une esthétique contemporaine. Conçu pour le confort, la durabilité et l’efficacité énergétique, il valorise chaque espace de vie avec élégance et fonctionnalité.",
        standardEquipment: [
          "Vitrage double chambre Ug = 0,5 W/(m²K)",
          "Intercalaire chaud Swisspacer Ultimate pour une meilleure isolation",
          "Soudure V‑Perfect pour des angles impeccables",
          "Joints périphériques et de vitrage en noir ou gris",
          "Joint central noir pour une étanchéité supplémentaire",
          "Large sélection de teintes PVC plaxé",
          "Poignée en aluminium à l’intérieur",
          "Poignée de tirage en aluminium à l’extérieur",
        ],
      },
      structureImages: [],
    },
    {
      name: "IGLO SLIDE",
      tagline: "Misez sur des solutions éprouvées",
      heroVideo: "./assets/Products/TerraceSystems/IGLO SLIDE/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "Joints noirs avec brosses d’étanchéité",
        thermalTransmittance: "Ug = 1.1 W/(m²K)",
        numberOfChambers: 3,
        installationDepth: "82 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO SLIDE",
        detailVideo: "./assets/Products/TerraceSystems/IGLO SLIDE/detail.mp4",
        description:
          "Le système IGLO SLIDE est conçu pour la fabrication de portes de terrasse et de fenêtres coulissantes alliant fonctionnalité, durabilité et simplicité d’usage. Idéal pour les espaces où les solutions traditionnelles ne conviennent pas, il assure fiabilité et confort sur le long terme. Parfait pour les intérieurs ne nécessitant pas de fortes valeurs d’isolation thermique, avec un style moderne et raffiné.",
        standardEquipment: [
          "Quincaillerie Siegenia avec chariots réglables en hauteur",
          "3 types de poignées aluminium",
          "Vitrage 24 mm, double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Intercalaire en acier galvanisé",
          "Soudure V‑Perfect pour des angles sans défaut",
          "Joints brosse pour une manœuvre fluide et une meilleure protection",
          "Joints noirs pour une esthétique raffinée",
          "Renfort acier 2 mm pour cadre et ouvrant",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-SLIDE",
      tagline: "Misez sur des solutions éprouvées",
      heroVideo: "./assets/Products/TerraceSystems/MB-SLIDE/hero.PNG",
      specs: {
        soundInsulation: null,
        gaskets: null,
        thermalTransmittance: null,
        numberOfChambers: null,
        installationDepth: "50 mm / 97 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-SLIDE",
        detailVideo: "./assets/Products/TerraceSystems/MB-SLIDE/detail.mp4",
        description:
          "Le système MB‑SLIDE est conçu pour la réalisation de portes et fenêtres coulissantes avec isolation thermique. Grâce à sa conception, il peut être intégré dans des murs en brique, des façades aluminium, des jardins d’hiver ou des châssis. Il offre une excellente durabilité, une manœuvre fluide et des fonctionnalités modernes pour des projets architecturaux polyvalents. Dimensions maximales de vantail : hauteur jusqu’à 2500 mm, largeur jusqu’à 1800 mm, poids max 160 kg.",
        standardEquipment: [
          "Profils aluminium avec isolation thermique",
          "Système coulissant compatible avec murs en brique, façades et jardins d’hiver",
          "Mécanisme coulissant fluide et durable",
          "Dimensions maximales de vantail : H 2500 mm, L 1800 mm",
          "Poids maximum du vantail : 160 kg",
          "Option d’intégration avec systèmes de façade ou châssis",
        ],
      },
      structureImages: [],
    },
    {
      name: "COR VISION",
      tagline: "La beauté du minimalisme",
      heroVideo: "./assets/Products/TerraceSystems/COR VISION/hero.PNG",
      specs: {
        soundInsulation: "dB = 41",
        gaskets: null,
        thermalTransmittance: "Uw = 1,3 W/(m²K)*",
        numberOfChambers: null,
        installationDepth: "116 mm / 182 mm",
        profileClass: null,
      },
      detailSection: {
        title: "COR VISION",
        detailVideo: "./assets/Products/TerraceSystems/COR VISION/detail.PNG",
        description:
          "Le système coulissant minimaliste COR VISION avec barrière thermique offre un éclairage intérieur maximal avec une structure aluminium presque invisible. La largeur du montant n’est que de 20 mm, pour un design élégant et épuré. Possibilité de dissimuler complètement le cadre afin de laisser la lumière et l’esthétique dominer l’espace, tout en conservant d’excellentes performances énergétiques et acoustiques.",
        standardEquipment: [
          "Système coulissant aluminium minimaliste avec barrière thermique",
          "Montant extrêmement étroit de 20 mm pour une surface vitrée maximale",
          "Option de dissimulation du cadre dans la structure",
          "Haute isolation acoustique jusqu’à 41 dB",
          "Transmission thermique Uw = 1,3 W/(m²K)*",
          "Vitrages de 26–30 mm pour une isolation optimale",
          "Mécanisme coulissant fluide et durable",
        ],
      },
      structureImages: [],
    },
    {
      name: "COR VISION PLUS",
      tagline: "La beauté du minimalisme",
      heroVideo: "./assets/Products/TerraceSystems/COR VISION PLUS/hero.PNG",
      specs: {
        soundInsulation: "dB = 43",
        gaskets: null,
        thermalTransmittance: "Uw = 0,9 W/(m²K)*",
        numberOfChambers: null,
        installationDepth: "180 mm / 278 mm",
        profileClass: null,
      },
      detailSection: {
        title: "COR VISION PLUS",
        detailVideo:
          "./assets/Products/TerraceSystems/COR VISION PLUS/detail.PNG",
        description:
          "Le système COR VISION PLUS incarne la quintessence du minimalisme. Conçu pour des portes coulissantes grand format avec vantaux jusqu’à 4 m de hauteur, il associe esthétique raffinée et performances thermiques et acoustiques avancées. Son montant central n’affiche que 25 mm de vue, et les cadres peuvent être encastrés dans le périmètre pour atteindre jusqu’à 94% de surface vitrée. En manœuvre manuelle (jusqu’à 400 kg) ou motorisée (jusqu’à 700 kg), il garantit confort, style et fluidité.",
        standardEquipment: [
          "Système coulissant minimaliste grand format avec rupture de pont thermique",
          "Montant central de seulement 25 mm pour un look moderne et élégant",
          "Cadres encastrés dans le périmètre pour jusqu’à 94% de surface vitrée",
          "Isolation acoustique jusqu’à 43 dB",
          "Transmission thermique Uw = 0,9 W/(m²K)*",
          "Capacité de vitrage jusqu’à 54 mm",
          "Manœuvre manuelle jusqu’à 400 kg ou motorisée jusqu’à 700 kg",
          "Rail caché en option pour une liaison au sol totalement intégrée",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-86 Fold Line HD",
      tagline:
        "Système pliant moderne pour des intérieurs spacieux et lumineux",
      heroVideo: "./assets/Products/TerraceSystems/MB-86 Fold Line HD/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 1,1 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "86 mm",
        profileClass: null,
      },
      detailSection: {
        title: "MB-86 Fold Line HD",
        detailVideo:
          "./assets/Products/TerraceSystems/MB-86 Fold Line HD/detail.mp4",
        description:
          "Le système MB‑86 Fold Line HD est une solution parfaite pour les vitrages grand format tels que balcons ou terrasses. Il combine isolation thermique exceptionnelle, design moderne et grande durabilité. Le mécanisme pliant assure une ouverture maximale et une polyvalence idéale pour les applications résidentielles et commerciales.",
        standardEquipment: [
          "Système de porte pliante en aluminium durable pour grandes ouvertures",
          "Quincaillerie système pour un fonctionnement fluide et fiable",
          "Caches‑charnières disponibles en blanc, argent et noir",
          "Poignée aluminium pour une esthétique soignée et une grande durabilité",
          "Triple vitrage (2 chambres) rempli d’argon, Ug = 0,5 W/(m²K)",
          "Intercalaire en acier galvanisé pour une isolation améliorée",
          "2 joints EPDM (extérieur et intérieur) disponibles en noir",
          "Couleurs mates RAL : blanc (9016), anthracite (7016)",
        ],
      },
      structureImages: [],
    },
    {
      name: "SOFTLINE 68",
      tagline: "Portes pliantes en bois classiques aux performances modernes",
      heroVideo: "./assets/Products/TerraceSystems/SOFTLINE 68/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints",
        thermalTransmittance: "Uw = 1,04 W/(m²K)*",
        numberOfChambers: null,
        installationDepth: "68 mm",
        profileClass: null,
      },
      detailSection: {
        title: "SOFTLINE 68",
        detailVideo: "./assets/Products/TerraceSystems/SOFTLINE 68/detail.mp4",
        description:
          "Le système de porte pliante SOFTLINE 68 associe l’élégance intemporelle du bois à des technologies avancées pour un design durable et visuellement remarquable. Il assure une excellente isolation thermique et laisse entrer un maximum de lumière naturelle, idéal pour les espaces classiques comme contemporains.",
        standardEquipment: [
          "Système de porte pliante en bois de haute qualité au design avancé",
          "2 joints d’étanchéité durables assurant excellente isolation et acoustique",
          "Profondeur d’installation de 68 mm pour une stabilité fiable",
          "Esthétique bois classique associée à une fonctionnalité moderne",
          "Isolation thermique efficace avec Uw = 1,04 W/(m²K)*",
          "Mécanisme pliant pour une manœuvre fluide et un gain d’espace",
          "Idéal pour terrasses, balcons et grandes ouvertures",
        ],
      },
      structureImages: [],
    },
    {
      name: "IGLO ENERGY PSK",
      tagline: "Transformez votre espace",
      heroVideo: "./assets/Products/TerraceSystems/IGLO ENERGY PSK/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 0,65 W/(m²K)*",
        numberOfChambers: 7,
        installationDepth: "82 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO ENERGY PSK",
        detailVideo:
          "./assets/Products/TerraceSystems/IGLO ENERGY PSK/detail.mp4",
        description:
          "IGLO ENERGY PSK est un système de terrasse oscillo‑coulissant à 7 chambres conçu pour une efficacité énergétique exceptionnelle et une esthétique moderne. Sa structure innovante et ses technologies d’isolation avancées en font un choix idéal pour réduire les coûts de chauffage et améliorer le confort.",
        standardEquipment: [
          "Ferrures MACO SKB‑S System Standard pour ouvrants jusqu’à 160 kg",
          "Triple vitrage (2 chambres) rempli d’argon, Ug = 0,5 W/(m²K)",
          "Âme du profil en blanc",
          "Intercalaire en acier galvanisé, option Swisspacer Ultimate",
          "2 joints EPDM noirs (extérieur et intérieur) + 1 joint central en EPDM moussé",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort cadre acier 2 mm (plein/fermé) et renfort ouvrant en ‘C’",
          "Poignée en aluminium",
          "Couvre‑rail disponible en 4 couleurs : argent, blanc, brun clair, brun",
          "Habillage sous appui PVC 5 chambres avec joint",
        ],
      },
      structureImages: [],
    },
    {
      name: "IGLO ENERGY CLASSIC PSK",
      tagline: "Profitez de chaque rayon de soleil",
      heroVideo:
        "./assets/Products/TerraceSystems/IGLO ENERGY CLASSIC PSK/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 0,66 W/(m²K)*",
        numberOfChambers: 7,
        installationDepth: "82 mm",
        profileClass: "A",
      },
      detailSection: {
        title: "IGLO ENERGY CLASSIC PSK",
        detailVideo:
          "./assets/Products/TerraceSystems/IGLO ENERGY CLASSIC PSK/detail.mp4",
        description:
          "IGLO ENERGY CLASSIC PSK est un système oscillo‑coulissant à 7 chambres avec profil de classe A fabriqué exclusivement à partir de matériaux vierges. Ce système propriétaire laisse entrer un maximum de lumière dans les petites comme les grandes pièces tout en maintenant une excellente isolation thermique, permettant de réduire significativement les coûts de chauffage.",
        standardEquipment: [
          "Ferrures MACO SKB‑S System Standard pour ouvrants jusqu’à 160 kg",
          "Triple vitrage (2 chambres) rempli d’argon, Ug = 0,5 W/(m²K)",
          "Âme du profil en blanc",
          "Intercalaire en acier galvanisé, option Swisspacer Ultimate",
          "2 joints EPDM noirs (extérieur et intérieur) + 1 joint central en EPDM moussé",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort cadre acier 2 mm (plein/fermé) et renfort ouvrant en ‘C’",
          "Poignée en aluminium",
          "Couvre‑rail disponible en 4 couleurs : argent, blanc, brun clair, brun",
          "Habillage sous appui PVC 5 chambres avec joint",
        ],
      },
      structureImages: [],
    },
    {
      name: "IGLO 5 PSK",
      tagline: "Choisissez des solutions modernes et éprouvées",
      heroVideo: "./assets/Products/TerraceSystems/IGLO 5 PSK/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0,81 W/(m²K)*",
        numberOfChambers: 5,
        installationDepth: "70 mm",
      },
      detailSection: {
        title: "IGLO 5 PSK",
        detailVideo: "./assets/Products/TerraceSystems/IGLO 5 PSK/detail.mp4",
        description:
          "Le système de terrasse oscillo‑coulissant IGLO 5 PSK assure un éclairage optimal des pièces, petites ou grandes. Il se distingue par sa forte isolation thermique et sa structure durable, avec de nombreuses options de personnalisation pour s’adapter aux styles architecturaux.",
        standardEquipment: [
          "Ferrures MACO SKB‑S System Standard pour ouvrants jusqu’à 160 kg",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Couvre‑rail disponible en 4 couleurs : argent, blanc, brun clair, brun",
          "Âme du profil en blanc",
          "Intercalaire en acier galvanisé, option Swisspacer Ultimate",
          "Hauteur du profil de cadre 75 mm",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort cadre acier 1,5 mm (plein/fermé) et renfort ouvrant acier 2 mm en ‘C’",
          "Poignée en aluminium, option serrure à clé",
          "Habillage sous appui PVC 5 chambres avec joint",
        ],
      },
      structureImages: [],
    },
    {
      name: "IGLO 5 CLASSIC PSK",
      tagline: "Qualité éprouvée",
      heroVideo: "./assets/Products/TerraceSystems/IGLO 5 CLASSIC PSK/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0,81 W/(m²K)*",
        numberOfChambers: 5,
        installationDepth: "24-40 mm",
      },
      detailSection: {
        title: "IGLO 5 CLASSIC PSK",
        detailVideo:
          "./assets/Products/TerraceSystems/IGLO 5 CLASSIC PSK/detail.mp4",
        description:
          "Une solution parfaite offrant un apport lumineux généreux pour les petites comme les grandes pièces tout en conservant une excellente isolation thermique. IGLO 5 CLASSIC PSK associe fonctionnalité moderne et durabilité éprouvée pour des performances et un confort durables.",
        standardEquipment: [
          "Ferrures MACO SKB‑S System Standard pour ouvrants jusqu’à 160 kg",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Couvre‑rail disponible en 4 couleurs : argent, blanc, brun clair, brun",
          "Âme du profil en blanc",
          "Intercalaire en acier galvanisé, option Swisspacer Ultimate",
          "Hauteur du profil de cadre 75 mm",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort cadre acier 1,5 mm (plein/fermé) et renfort ouvrant acier 2 mm en ‘C’",
          "Poignée en aluminium, option serrure à clé",
          "Habillage sous appui PVC 5 chambres avec joint",
        ],
      },
      structureImages: [],
    },
    {
      name: "IGLO LIGHT PSK",
      tagline: "Encore plus de lumière naturelle",
      heroVideo: "./assets/Products/TerraceSystems/IGLO LIGHT PSK/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints EPDM",
        thermalTransmittance: "Uw = 0,84 W/(m²K)*",
        numberOfChambers: 5,
        installationDepth: "70 mm",
      },
      detailSection: {
        title: "IGLO LIGHT PSK",
        detailVideo:
          "./assets/Products/TerraceSystems/IGLO LIGHT PSK/detail.mp4",
        description:
          "Un système de terrasse unique conçu pour offrir un maximum de lumière naturelle tout en conservant une excellente efficacité énergétique. IGLO LIGHT PSK combine un design épuré et une fonctionnalité fiable, pour un grand confort et un style séduisant dans les espaces modernes.",
        standardEquipment: [
          "Ferrures MACO SKB‑S System Standard pour ouvrants jusqu’à 160 kg",
          "Double vitrage (1 chambre) rempli d’argon, Ug = 1,1 W/(m²K)",
          "Couvre‑rail disponible en 4 couleurs : argent, blanc, brun clair, brun",
          "Âme du profil en blanc",
          "Intercalaire en acier galvanisé, option Swisspacer Ultimate",
          "Hauteur du profil de cadre 75 mm",
          "2 joints EPDM noirs (extérieur et intérieur)",
          "Remplissage de la gorge inférieure de quincaillerie",
          "Renfort cadre acier 1,5 mm (plein/fermé) et renfort ouvrant acier 2 mm en ‘C’",
          "Poignée en aluminium, option serrure à clé",
          "Habillage sous appui PVC 5 chambres avec joint",
        ],
      },
      structureImages: [],
    },
    {
      name: "MB-70 and MB-70HI PSK",
      tagline: "La perfection dans chaque détail",
      heroVideo:
        "./assets/Products/TerraceSystems/MB-70 and MB-70HI PSK/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints EPDM",
        thermalTransmittance: "Uw = 0,8 W/(m²K)*",
        numberOfChambers: 3,
        installationDepth: "70 mm",
        glassThermalInsulation: "24-53 mm",
      },
      detailSection: {
        title: "MB-70 and MB-70HI PSK",
        detailVideo:
          "./assets/Products/TerraceSystems/MB-70 and MB-70HI PSK/detail.mp4",
        description:
          "Un système de terrasse conçu pour transformer les intérieurs et mettre en valeur le caractère architectural de tout bâtiment. MB‑70 et MB‑70HI PSK offrent d’excellentes performances, une grande durabilité et des options de personnalisation appréciées dans le monde entier, combinant design élégant, isolation avancée et fonctionnalité.",
        standardEquipment: [
          "Système de profilés aluminium de haute qualité",
          "3 joints EPDM pour une isolation et une étanchéité supérieures",
          "Vitrages à isolation thermique à partir de Ug = 0,8 W/(m²K)*",
          "Profondeur d’installation de 70 mm",
          "Compatible avec des épaisseurs de vitrage de 24 à 53 mm",
          "Mécanisme oscillo‑coulissant durable et fluide",
          "Poignée en aluminium au design soigné",
          "Option d’isolation renforcée en version HI pour une meilleure efficacité énergétique",
          "Large choix de couleurs RAL",
        ],
      },
      structureImages: [],
    },
    {
      name: "Softline PSK",
      tagline: "Force et beauté de la nature",
      heroVideo: "./assets/Products/TerraceSystems/Softline PSK/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "2 joints",
        thermalTransmittance: "Uw = 0,73 - 1,06 W/(m²K)*",
        numberOfChambers: null,
        installationDepth: "68/78/88 mm",
        glassThermalInsulation: null,
      },
      detailSection: {
        title: "Softline PSK",
        detailVideo: "./assets/Products/TerraceSystems/Softline PSK/detail.mp4",
        description:
          "Cette porte de terrasse en bois à relevage‑coulissant est conçue pour les grands vitrages afin d’apporter une lumière abondante et de la chaleur. Fabriqué avec des technologies de production avancées, le système Softline PSK offre une esthétique, une durabilité et une qualité de fabrication exceptionnelles, mettant en valeur la force et l’élégance naturelles du bois.",
        standardEquipment: [
          "Construction en bois lamellé de haute qualité (épaisseurs 68/78/88 mm)",
          "2 joints durables assurant une excellente étanchéité",
          "Transmission thermique Uw = 0,73–1,06 W/(m²K)*",
          "Mécanisme de coulissement et de relevage fluide pour une utilisation aisée",
          "Seuil aluminium avec rupteur thermique pour une meilleure isolation",
          "Disponible en plusieurs finitions bois et teintes",
          "Options de vitrage et de poignées personnalisables",
          "Revêtements écologiques garantissant durabilité et résistance",
        ],
      },
      structureImages: [],
    },
    {
      name: "DUOLINE PSK",
      tagline: "Harmonie classique du bois et de l’aluminium",
      heroVideo: "./assets/Products/TerraceSystems/DUOLINE PSK/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: "3 joints",
        thermalTransmittance: "Uw = 0,71–0,93 W/(m²K)*",
        numberOfChambers: null,
        installationDepth: "82/92 mm",
        glassThermalInsulation: null,
      },
      detailSection: {
        title: "DUOLINE PSK",
        detailVideo: "./assets/Products/TerraceSystems/DUOLINE PSK/detail.mp4",
        description:
          "Un système de porte oscillo‑coulissante unique combinant la chaleur du bois à la durabilité de l’aluminium. Le système DUOLINE PSK séduit par son design élégant, son excellente isolation et sa qualité de fabrication supérieure — un équilibre parfait entre performances modernes et esthétique intemporelle.",
        standardEquipment: [
          "Structure hybride bois‑aluminium de haute qualité",
          "3 joints durables pour une étanchéité et une isolation renforcées",
          "Transmission thermique Uw = 0,71–0,93 W/(m²K)*",
          "Fonction oscillo‑coulissante pour une manœuvre fluide et un gain d’espace",
          "Seuil aluminium avec rupteur thermique pour une meilleure isolation",
          "Large choix de couleurs RAL et de finitions bois",
          "Paquets de vitrage personnalisables pour davantage d’efficacité énergétique",
          "Poignée aluminium premium et détails de design modernes",
        ],
      },
      structureImages: [],
    },
  ],
  shutters: [
    // Shutters
    {
      name: "Volets roulants en aluminium",
      tagline: "Préservez votre confort et votre intimité",
      heroVideo:
        "./assets/Products/Shutters/Volets roulants en aluminium/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: null,
        thermalTransmittance: null,
        numberOfChambers: null,
        installationDepth: null,
        profileClass: null,
      },
      detailSection: {
        title: "Volets roulants en aluminium",
        detailVideo:
          "./assets/Products/Shutters/Volets roulants en aluminium/detail.mp4",
        description:
          "Optez pour des solutions modernes et éprouvées afin de réduire vos factures de chauffage et d’énergie tout en préservant votre intimité et votre sécurité. Les volets roulants en aluminium offrent une excellente protection contre le soleil, le bruit et les regards indiscrets, garantissant un confort maximal et une haute efficacité énergétique. Ils peuvent également être intégrés facilement à des systèmes Smart Home pour plus de confort et d’automatisation.",
        standardEquipment: [
          "Profils en aluminium durables assurant une performance longue durée",
          "Haute efficacité d’isolation pour réduire les coûts énergétiques",
          "Options de commande manuelle ou motorisée",
          "Compatibles avec les systèmes Smart Home pour un pilotage à distance",
          "Disponible dans une large gamme de couleurs et finitions RAL",
          "Protection efficace contre l’ensoleillement excessif et les bruits extérieurs",
          "Intimité renforcée et sécurité améliorée",
        ],
      },
      structureImages: [],
    },
    {
      name: "Volets roulants en PVC",
      tagline: "Choisissez la modernité",
      heroVideo: "./assets/Products/Shutters/Volets roulants en PVC/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: null,
        thermalTransmittance: null,
        numberOfChambers: null,
        installationDepth: null,
        profileClass: null,
      },
      detailSection: {
        title: "Volets roulants en PVC",
        detailVideo:
          "./assets/Products/Shutters/Volets roulants en PVC/detail.mp4",
        description:
          "Une solution idéale toute l’année pour garantir intimité, confort et économies d’énergie. Les volets roulants en PVC posés en coffre apportent une protection efficace contre le soleil, le bruit et les conditions extérieures tout en conservant une esthétique moderne et épurée. Parfaits pour améliorer l’efficacité énergétique, ils s’intègrent aisément aux systèmes Smart Home pour un confort maximal.",
        standardEquipment: [
          "Construction en PVC durable garantissant une fiabilité à long terme",
          "Excellente isolation pour des économies d’énergie toute l’année",
          "Commandes manuelles ou motorisées disponibles",
          "Compatibles avec les systèmes d’automatisation Smart Home",
          "Disponible dans une gamme de couleurs et finitions RAL",
          "Occultation efficace et maîtrise de l’intimité",
          "Protection contre le bruit extérieur et les intempéries",
        ],
      },
      structureImages: [],
    },
    {
      name: "Volets roulants avec caisson en polystyrène",
      tagline: null,
      heroVideo:
        "./assets/Products/Shutters/Volets roulants avec caisson en polystyrène/hero.mp4",
      specs: {
        soundInsulation: null,
        gaskets: null,
        thermalTransmittance: null,
        numberOfChambers: null,
        installationDepth: null,
        profileClass: null,
      },
      detailSection: {
        title: "Volets roulants avec caisson en polystyrène",
        detailVideo:
          "./assets/Products/Shutters/Volets roulants avec caisson en polystyrène/detail.mp4",
        description:
          "Les volets roulants avec caisson en polystyrène sont conçus pour offrir une excellente isolation thermique et acoustique, gage du confort recherché. Leur design moderne assure une protection optimale contre les bruits extérieurs et les déperditions de chaleur, tout en conservant une apparence propre et esthétique. Ils s’intègrent facilement aux systèmes Smart Home pour une utilisation pratique.",
        standardEquipment: [
          "Performances élevées d’isolation thermique et acoustique",
          "Caisson en polystyrène durable pour une meilleure efficacité",
          "Commandes manuelles ou motorisées disponibles",
          "Compatibles avec les systèmes d’automatisation Smart Home",
          "Disponible dans une large gamme de couleurs et de designs",
          "Protection contre l’ensoleillement excessif et les conditions extérieures",
          "Intimité et confort accrus en toute saison",
        ],
      },
      structureImages: [],
    },
  ],
};

export default products;
