const products = [
  {
    name: "IGLO EDGE",
    tagline: "Technology That Impresses",
    heroVideo: "./assets/Products/IGLO EDGE/hero.mp4",
    specs: {
      soundInsulation: "36-47 dB",
      gaskets: "3 EPDM gaskets",
      thermalTransmittance: "Uw = 0.66 W/(m²K)*",
      numberOfChambers: 7,
      installationDepth: "82 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO EDGE",
      detailVideo: "./assets/Products/IGLO EDGE/detail.mp4",
      description:
        "Our new, most technologically advanced window is distinguished by an excellent thermal insulation parameter of Uw = 0.66 W/(m2K)* and a modern, angular profile shape. The extremely good thermal insulation parameters are due, among other things, to the 7-chamber profile design and 3 EPDM gaskets, including the central gasket.",
      standardEquipment: [
        "Double-chamber glazing package Ug = 0.5 W/(m2K)",
        "Swisspacer Ultimate plastic warm frame",
        "V-perfect weld",
        "4 anti-theft strikers according to the size of the sash and the hardware system",
        "Microventilation",
        "DUBLIN aluminium window handle",
        "Handle misplacement locking mechanism",
        "Perimeter, glazing and central gaskets in black or grey",
        "Filling of the lower hardware groove",
        "Sill trim",
        "Wide selection of PVC veneer colours",
        "3 profile colours to choose from: white, brown or anthracite",
      ],
    },
    structureImages: [
      "./assets/Products/IGLO EDGE/structure1.png",
      "./assets/Products/IGLO EDGE/structure2.png",
    ],
  },
  {
    name: "IGLO Energy",
    tagline: "",
    heroVideo: "./assets/Products/IGLO Energy/hero.mp4",
    specs: {
      soundInsulation: "37-46 dB",
      gaskets: "3 EPDM gaskets",
      thermalTransmittance: "Uw = 0.71 W/(m2K)*",
      numberOfChambers: 7,
      installationDepth: "82 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO Energy",
      detailVideo: "./assets/Products/IGLO Energy/detail.mp4",
      description:
        "An innovative and original 7-chamber A-class profile made exclusively of primary materials. The world's first system using a central gasket made of foamed EPDM to ensure the best energy efficiency parameters. Iglo Energy windows also stand out for their perfect parameters in terms of water tightness, microventilation and resistance to wind.",
      standardEquipment: [
        "Double-chamber glazing package Ug = 0.5 W/(m2K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "4 anti-theft strikers according to the size of the sash and the hardware system",
        "Microventilation",
        "Aluminium window handle",
        "Handle misplacement locking mechanism",
        "Perimeter, glazing and central gaskets in black or grey",
        "Filling of the lower hardware groove",
        "Sill trim",
        "Wide selection of PVC veneer colours",
        "Profile available in two colours: white, brown",
      ],
    },
    structureImages: [
      "./assets/Products/IGLO Energy/structure1.png",
      "./assets/Products/IGLO Energy/structure2.png",
    ],
  },
  {
    name: "IGLO Energy Classic",
    tagline: "The best parameters concealed in modern design",
    heroVideo: "./assets/Products/IGLO Energy Classic/hero.mp4",
    specs: {
      soundInsulation: "36-42 dB",
      gaskets: "3 EPDM gaskets",
      thermalTransmittance: "Uw = 0.73 W/(m2K)*",
      numberOfChambers: 7,
      installationDepth: "82 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO Energy Classic",
      detailVideo: "./assets/Products/IGLO Energy Classic/detail.mp4",
      description:
        "A unique design where you can choose the square-shaped glazing bead to reflect the latest architectural trends. The remarkable thermal insulation parameters are ensured by the optimum 7-chamber profile structure, a specially designed sealing system made of foamed EPDM and glass packages with high thermal insulation parameters.",
      standardEquipment: [
        "double-chamber glazing package Ug = 0,5 W/(m2K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "V-perfect weld",
        "4 anti-theft strikers according to the size of the sash and the hardware system",
        "microventilation",
        "aluminium window handle",
        "handle misplacement locking mechanism",
        "perimeter, glazing and central gaskets in black or grey",
        "filling of the lower hardware groove",
        "sill trim",
        "wide selection of pvc veneer colours",
      ],
      profileColors: ["white", "anthracite", "bronze"],
    },
    structureImages: [
      "./assets/Products/IGLO Energy Classic/structure1.png",
      "./assets/Products/IGLO Energy Classic/structure2.png",
    ],
  },
  {
    name: "IGLO ENERGY ALUCOVER",
    tagline: "Redefining Design Excellence",
    heroVideo: "./assets/Products/IGLO ENERGY ALUCOVER/hero.mp4",
    specs: {
      soundInsulation: "36 - 42 dB*",
      gaskets: "3 EPDM gaskets",
      thermalTransmittance: "Uw = 0,76 W/(m2K)*",
      numberOfChambers: 7,
      installationDepth: "93 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO ENERGY ALUCOVER",
      detailVideo: "./assets/Products/IGLO ENERGY ALUCOVER/detail.mp4",
      description:
        "Experience the fusion of cutting-edge thermal insulation performance and contemporary design with Iglo Energy Alucover. Embrace boundless creativity with an extensive palette of colors, empowering you to fashion a unique and personalized style for every interior or building facade.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 4 anti-theft strikers with Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 4 colours: white, silver, light brown, brown",
        "Dublin window handle",
        "3-glazed (2-chamber) units infilled with argon gas, with Ug = 0.5 W/(m²K)",
        "Swisspacer Ultimate edge",
        "Rectangular glazing bead",
        "V-Perfect weld",
        "2 EPDM gaskets (external and internal) + 1 central gasket made of foamed EPDM, gaskets available in black",
        "Gasket filling the lower fittings groove",
        "2 mm full (closed) steel frame reinforcement, 'C' shaped steel sash reinforcement",
        "RAL matt varnish",
        "5-chamber PVC under-sill trim with gasket",
      ],
    },
    structureImages: [
      "./assets/Products/IGLO ENERGY ALUCOVER/structure1.png",
      "./assets/Products/IGLO ENERGY ALUCOVER/structure2.png",
    ],
  },
  {
    name: "IGLO 5",
    tagline: "High quality at an attractive price",
    heroVideo: "./assets/Products/IGLO 5/hero.mp4",
    specs: {
      soundInsulation: "36-44 dB",
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0,89 W/(m2K)*",
      numberOfChambers: 5,
      installationDepth: "70 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO 5",
      detailVideo: "./assets/Products/IGLO 5/detail.mp4",
      description:
        "A 5-chamber system featuring very good thermal insulation parameters. Our innovative solution is based on a snow-white A-class profile made exclusively of primary materials to ensure the highest quality. These windows are perfect for both warm and cold climates.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers with Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "sash lifter (lifting mishandling device - depending on window height)",
        "microventilation in tilt and turn windows",
        "hinge covers in 4 colours: white, silver, light brown, brown",
        "aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "galvanised steel glass-pane spacer optional Swisspacer Ultimate glass-pane spacer",
        "2 EPDM gaskets in black (external and internal)",
        "gasket filling the lower fittings groove",
        "1.5 mm steel reinforcement for frame and sash (2 mm for balcony door sash), 'c'-shaped",
        "profile core in white",
        "5-chamber PVC under-sill trim with gasket",
        "Profile available in two colours: white and brown",
      ],
    },
    structureImages: [
      "./assets/Products/IGLO 5/structure1.png",
      "./assets/Products/IGLO 5/structure2.png",
    ],
  },
  {
    name: "IGLO 5 Classic",
    tagline: "Proven solutions mean customer satisfaction",
    heroVideo: "./assets/Products/IGLO 5 Classic/hero.mp4",
    specs: {
      soundInsulation: "34-42 dB",
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0.83 W/(m²K)*",
      numberOfChambers: 5,
      installationDepth: "70 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "IGLO 5 Classic",
      detailVideo: "./assets/Products/IGLO 5 Classic/detail.mp4",
      description:
        "Windows appreciated by Customers across the globe. They feature not only very good thermal insulation parameters but also excellent aesthetic values. With a wide range of Renolit veneers and numerous additional options, we can create the windows that will meet the expectations of the most demanding Customers.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers with Silber-Look anticorrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 4 colours: white, silver, light brown, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Galvanised steel glass-pane spacer optional Swisspacer Ultimate glass-pane spacer",
        "2 EPDM gaskets in black (external and internal)",
        "Gasket filling the lower fittings groove",
        "1.5 mm steel reinforcement for frame and sash (2 mm for balcony door sash), 'c'-shaped",
        "Profile core in white",
        "5-chamber PVC under-sill trim with gasket",
        "The profile is available in three colours: white, anthracite and bronze",
      ],
    },
    structureImages: [
      "./assets/Products/IGLO 5 Classic/structure1.png",
      "./assets/Products/IGLO 5 Classic/structure2.png",
    ],
  },
  {
    name: "IGLO Light",
    tagline: "Even more daylight",
    heroVideo: "./assets/Products/IGLO Light/hero.mp4",
    specs: {
      soundInsulation: "34 dB",
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0,88 W/(m2K)*",
      numberOfChambers: 5,
      installationDepth: "70 mm",
      profileClass: null,
    },
    detailSection: {
      title: "IGLO Light",
      tagline: "Even more daylight",
      detailVideo: "./assets/Products/IGLO Light/detail.mp4",
      description:
        "This 5-chamber and original system stands out for its high aesthetic values and thin frame and sash profiles. Compared to traditional systems, it has a 32% thinner movable post to improve the amount of daylight that reaches a room.",
      standardEquipment: [
        "MACO MULTI-MATIC KS fittings with 2 anti-theft strikers with Silber-Look anti-corrosion coating for long-lasting protection and smooth operation of the fitting",
        "Sash lifter (lifting mishandling device - depending on window height)",
        "Microventilation in tilt and turn windows",
        "Hinge covers in 4 colours: white, silver, light brown, brown",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "Glass-pane spacer made of galvanised steel",
        "2 EPDM gaskets in black (external and internal)",
        "Gasket filling the lower fittings groove",
        "1.5 mm steel reinforcement for frame and sash (2mm for balcony door sash), 'c'-shaped",
        "Profile core in white",
        "5-chamber PVC under-sill trim with gasket",
        "V-Perfect welding",
      ],
    },
    structureImages: [
      "./assets/Products/IGLO Light/structure1.png",
      "./assets/Products/IGLO Light/structure2.png",
    ],
  },
  {
    name: "Iglo EXT",
    tagline: "Modern PVC balcony windows and doors that open outwards",
    heroVideo: "./assets/Products/IGLO EXT/hero.mp4",
    specs: {
      soundInsulation: "34 - 35 dB*",
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0.89 W/(m²K)*",
      numberOfChambers: 5,
      installationDepth: "70 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "Iglo EXT",
      detailVideo: "./assets/Products/IGLO EXT/detail.mp4",
      description:
        "Balcony windows and doors that open outwards stand out for their modern design and excellent thermal insulation performance. As standard, these windows have hidden fittings (invisible when closed), while balcony doors have door (surface) fittings. The Iglo EXT window and door system is ideal for those looking for modern design and high aesthetic values.",
      standardEquipment: [
        "Double-chamber glazing package Ug = 1.1 W/(m²K)",
        "Concealed MACO Multi-Power fittings in the window (invisible hinges when the window is closed), door fittings on balcony windows or balcony doors",
        "Double roller DM20 bolt for full (airtight) locking or locking with trickle ventilation",
        "Aluminium handle with double-sided insert",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "2 EPDM gaskets in black (external and internal)",
        "Gasket filling the lower fittings groove",
        "1.5 mm full (closed), steel, 'c'-shaped frame and sash reinforcement (2 mm for balcony door sashes)",
        "Profile core in white",
        "5-chamber PVC under-sill trim with gasket",
      ],
    },
    structureImages: [
      "./assets/Products/IGLO EXT/structure1.png",
      "./assets/Products/IGLO EXT/structure2.png",
    ],
  },
  {
    name: "Iglo Premier",
    tagline: "Modern outward opening tilt and turn windows",
    heroVideo: "./assets/Products/IGLO PREMIER/hero.mp4",
    specs: {
      soundInsulation: "34 - 35 dB*",
      gaskets: "2 EPDM gaskets",
      thermalTransmittance: "Uw = 0.89 W/(m²K)*",
      numberOfChambers: 5,
      installationDepth: "70 mm",
      profileClass: "A",
    },
    detailSection: {
      title: "Iglo Premier",
      detailVideo: "./assets/Products/IGLO PREMIER/detail.mp4",
      description:
        "Original outward opening tilt and turn windows are based on an extremely warm 5-chamber A-class profile made exclusively of primary material. The system comes with double sealing and reliable fittings to ensure high utility values for years to come.",
      standardEquipment: [
        "Scissor hinges (invisible when the window is closed)",
        "Double roller DM20 bolt for full (airtight) locking or locking with trickle ventilation",
        "Double-chamber glazing package Ug = 1.1 W/(m²K)",
        "Aluminium handle",
        "2-glazed (1-chamber) units infilled with argon gas with Ug = 1.1 W/(m²K)",
        "Swisspacer Ultimate plastic warm frame - as a free elective option",
        "2 EPDM gaskets in black (external and internal)",
        "Gasket filling the lower fittings groove",
        "1.5 mm full (closed), steel, 'c'-shaped frame and sash reinforcement (2 mm for balcony door sashes)",
        "Profile core in white",
        "5-chamber PVC under-sill trim with gasket",
      ],
    },
    structureImages: [
      "./assets/Products/IGLO PREMIER/structure1.png",
      "./assets/Products/IGLO PREMIER/structure2.png",
    ],
  },
];

export default products;
